import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common'
import { Prisma, RecordStatus as DatabaseRecordStatus } from '@shulefinance/database'
import type { AuthenticatedUser, RequestContext } from '../auth/auth.types'
import { DatabaseService } from '../database/database.service'
import { CreateExpenseDto, ExpenseQueryDto, ReviewBudgetDto, ReviewExpenseDto, SaveBudgetDto, SaveCategoryDto, SaveVendorDto } from './dto/expenditure.dto'

const expenseInclude={requestedBy:true,approvals:{include:{decidedBy:true},orderBy:{decidedAt:'desc'} as const},documents:true,vendorRecord:true,categoryRecord:true} as const
const budgetInclude={term:{include:{academicYear:true}},items:true,createdBy:true,approvedBy:true} as const
const RecordStatus:Record<string,any>=DatabaseRecordStatus
@Injectable()
export class ExpenditureService{
 constructor(private readonly db:DatabaseService){}
 async categories(user:AuthenticatedUser){const rows=await this.db.expenseCategory.findMany({where:{schoolId:user.schoolId,isActive:true},orderBy:{name:'asc'}});return{categories:rows}}
 async createCategory(user:AuthenticatedUser,dto:SaveCategoryDto){const category=await this.db.expenseCategory.upsert({where:{schoolId_name:{schoolId:user.schoolId,name:dto.name.trim()}},create:{schoolId:user.schoolId,name:dto.name.trim()},update:{isActive:true}});return{category}}
 async vendors(user:AuthenticatedUser){const rows=await this.db.vendor.findMany({where:{schoolId:user.schoolId,isActive:true},orderBy:{name:'asc'}});return{vendors:rows}}
 async createVendor(user:AuthenticatedUser,dto:SaveVendorDto){const vendor=await this.db.vendor.upsert({where:{schoolId_name:{schoolId:user.schoolId,name:dto.name.trim()}},create:{schoolId:user.schoolId,name:dto.name.trim(),email:dto.email,phone:dto.phone},update:{email:dto.email,phone:dto.phone,isActive:true}});return{vendor}}
 async expenses(user:AuthenticatedUser,q:ExpenseQueryDto){const where:Prisma.ExpenseWhereInput={schoolId:user.schoolId,...(q.status?{status:q.status}:{}),...(q.search?{OR:[{expenseNumber:{contains:q.search,mode:'insensitive'}},{description:{contains:q.search,mode:'insensitive'}},{vendor:{contains:q.search,mode:'insensitive'}},{category:{contains:q.search,mode:'insensitive'}}]}:{})};const [rows,total]=await this.db.$transaction([this.db.expense.findMany({where,include:expenseInclude,orderBy:{createdAt:'desc'},skip:(q.page-1)*q.pageSize,take:q.pageSize}),this.db.expense.count({where})]);return{expenses:rows.map(row=>this.presentExpense(row)),pagination:{page:q.page,pageSize:q.pageSize,total,totalPages:Math.ceil(total/q.pageSize)}}}
 async createExpense(user:AuthenticatedUser,dto:CreateExpenseDto,ctx:RequestContext){const term=await this.activeTerm(user.schoolId);const number=`EXP-${new Date().getFullYear()}-${String((await this.db.expense.count({where:{schoolId:user.schoolId}}))+1).padStart(5,'0')}`;try{const row=await this.db.$transaction(async tx=>{const vendor=await tx.vendor.upsert({where:{schoolId_name:{schoolId:user.schoolId,name:dto.vendor.trim()}},create:{schoolId:user.schoolId,name:dto.vendor.trim()},update:{isActive:true}});const category=await tx.expenseCategory.upsert({where:{schoolId_name:{schoolId:user.schoolId,name:dto.category.trim()}},create:{schoolId:user.schoolId,name:dto.category.trim()},update:{isActive:true}});const created=await tx.expense.create({data:{schoolId:user.schoolId,termId:term.id,expenseNumber:number,description:dto.description.trim(),vendor:dto.vendor.trim(),category:dto.category.trim(),vendorId:vendor.id,categoryId:category.id,requestedById:user.id,amount:dto.amount,incurredAt:new Date(dto.incurredAt),paymentMethod:dto.paymentMethod,reference:dto.reference?.trim(),notes:dto.notes?.trim(),documents:dto.documentName?{create:{fileName:dto.documentName.trim(),storageKey:`pending/${crypto.randomUUID()}/${dto.documentName.trim()}`,mimeType:'application/octet-stream',size:0}}:undefined}});await tx.auditEvent.create({data:{schoolId:user.schoolId,actorId:user.id,action:'EXPENSE_REQUESTED',module:'Expenses',recordType:'Expense',recordId:created.id,after:{expenseNumber:number,amount:dto.amount,vendor:dto.vendor,category:dto.category},ipAddress:ctx.ipAddress,requestId:ctx.requestId}});return tx.expense.findUniqueOrThrow({where:{id:created.id},include:expenseInclude})});return{expense:this.presentExpense(row)}}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002')throw new ConflictException('Expense number collision; retry the request');throw error}}
 async reviewExpense(user:AuthenticatedUser,id:string,dto:ReviewExpenseDto,ctx:RequestContext){if(![RecordStatus.APPROVED,RecordStatus.REJECTED].includes(dto.decision))throw new BadRequestException('Decision must be APPROVED or REJECTED');const current=await this.db.expense.findFirst({where:{id,schoolId:user.schoolId},include:expenseInclude});if(!current)throw new NotFoundException('Expense not found');if(current.status!==RecordStatus.PENDING)throw new ConflictException('Only pending expenses can be reviewed');const row=await this.db.$transaction(async tx=>{await tx.expense.update({where:{id},data:{status:dto.decision,approvals:{create:{decision:dto.decision,note:dto.note.trim(),decidedById:user.id}}}});await tx.auditEvent.create({data:{schoolId:user.schoolId,actorId:user.id,action:`EXPENSE_${dto.decision}`,module:'Expenses',recordType:'Expense',recordId:id,before:{status:current.status},after:{status:dto.decision,note:dto.note},ipAddress:ctx.ipAddress,requestId:ctx.requestId}});return tx.expense.findUniqueOrThrow({where:{id},include:expenseInclude})});return{expense:this.presentExpense(row)}}
 async budgets(user:AuthenticatedUser){const rows=await this.db.budget.findMany({where:{schoolId:user.schoolId},include:budgetInclude,orderBy:{updatedAt:'desc'}});const actuals=await this.db.expense.groupBy({by:['termId','category'],where:{schoolId:user.schoolId,status:RecordStatus.APPROVED},_sum:{amount:true}});return{budgets:rows.map(row=>this.presentBudget(row,actuals))}}
 async saveBudget(user:AuthenticatedUser,id:string|null,dto:SaveBudgetDto,ctx:RequestContext){if(![RecordStatus.DRAFT,RecordStatus.PENDING].includes(dto.status))throw new BadRequestException('A budget can only be saved as DRAFT or PENDING');if(new Set(dto.items.map(x=>x.category.trim().toLowerCase())).size!==dto.items.length)throw new BadRequestException('Budget categories must be unique');const term=await this.db.term.findFirst({where:{name:dto.term,academicYear:{schoolId:user.schoolId,name:String(dto.year)}}});if(!term)throw new BadRequestException('Academic term not found');const current=id?await this.db.budget.findFirst({where:{id,schoolId:user.schoolId}}):null;if(id&&!current)throw new NotFoundException('Budget not found');if(current&&![RecordStatus.DRAFT,RecordStatus.PENDING].includes(current.status))throw new ConflictException('Approved or archived budgets cannot be edited');try{const row=await this.db.$transaction(async tx=>{let budget;if(current){await tx.budgetItem.deleteMany({where:{budgetId:id!}});budget=await tx.budget.update({where:{id:id!},data:{name:dto.name.trim(),termId:term.id,status:dto.status,items:{create:dto.items.map(x=>({category:x.category.trim(),allocated:x.allocated}))}}})}else budget=await tx.budget.create({data:{schoolId:user.schoolId,termId:term.id,name:dto.name.trim(),status:dto.status,createdById:user.id,items:{create:dto.items.map(x=>({category:x.category.trim(),allocated:x.allocated}))}}});await tx.auditEvent.create({data:{schoolId:user.schoolId,actorId:user.id,action:current?'BUDGET_UPDATED':'BUDGET_CREATED',module:'Budgets',recordType:'Budget',recordId:budget.id,after:{name:dto.name,status:dto.status,total:dto.items.reduce((s,x)=>s+x.allocated,0)},ipAddress:ctx.ipAddress,requestId:ctx.requestId}});return tx.budget.findUniqueOrThrow({where:{id:budget.id},include:budgetInclude})});return{budget:this.presentBudget(row,[])}}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002')throw new ConflictException('A budget with this name already exists for the term');throw error}}
 async reviewBudget(user:AuthenticatedUser,id:string,dto:ReviewBudgetDto,ctx:RequestContext){if(![RecordStatus.APPROVED,RecordStatus.REJECTED].includes(dto.decision))throw new BadRequestException('Decision must be APPROVED or REJECTED');const current=await this.db.budget.findFirst({where:{id,schoolId:user.schoolId}});if(!current)throw new NotFoundException('Budget not found');if(current.status!==RecordStatus.PENDING)throw new ConflictException('Only pending budgets can be reviewed');const row=await this.db.$transaction(async tx=>{if(dto.decision===RecordStatus.APPROVED)await tx.budget.updateMany({where:{schoolId:user.schoolId,termId:current.termId,status:RecordStatus.APPROVED,id:{not:id}},data:{status:RecordStatus.ARCHIVED}});await tx.budget.update({where:{id},data:{status:dto.decision,approvedById:user.id,approvedAt:new Date()}});await tx.auditEvent.create({data:{schoolId:user.schoolId,actorId:user.id,action:`BUDGET_${dto.decision}`,module:'Budgets',recordType:'Budget',recordId:id,before:{status:current.status},after:{status:dto.decision,note:dto.note||null},ipAddress:ctx.ipAddress,requestId:ctx.requestId}});return tx.budget.findUniqueOrThrow({where:{id},include:budgetInclude})});return{budget:this.presentBudget(row,[])}}
 private activeTerm(schoolId:string){return this.db.term.findFirst({where:{academicYear:{schoolId},status:'ACTIVE'},orderBy:{startsOn:'desc'}}).then(term=>{if(!term)throw new BadRequestException('Configure an active academic term first');return term})}
 private presentExpense(row:any){const review=row.approvals[0];return{id:row.id,expenseNumber:row.expenseNumber,description:row.description,category:row.categoryRecord?.name||row.category,vendor:row.vendorRecord?.name||row.vendor,amount:Number(row.amount),date:row.incurredAt,status:this.title(row.status),requestedBy:row.requestedBy?`${row.requestedBy.firstName} ${row.requestedBy.lastName}`:'System',approvedBy:review?.decidedBy?`${review.decidedBy.firstName} ${review.decidedBy.lastName}`:undefined,paymentMethod:row.paymentMethod?row.paymentMethod==='MPESA'?'M-Pesa':this.title(row.paymentMethod):undefined,reference:row.reference,document:row.documents[0]?.fileName,documents:row.documents,notes:row.notes,reviewNote:review?.note}}
 private presentBudget(row:any,actuals:any[]){const items=row.items.map((item:any)=>{const actual=actuals.find(x=>x.termId===row.termId&&x.category===item.category)?._sum.amount||0;return{id:item.id,category:item.category,allocated:Number(item.allocated),actual:Number(actual)}});return{id:row.id,name:row.name,term:row.term.name,termId:row.termId,year:Number(row.term.academicYear.name),items,status:this.title(row.status),createdBy:row.createdBy?`${row.createdBy.firstName} ${row.createdBy.lastName}`:'System',approvedBy:row.approvedBy?`${row.approvedBy.firstName} ${row.approvedBy.lastName}`:undefined,updatedAt:row.updatedAt,totalAllocated:items.reduce((s:number,x:any)=>s+x.allocated,0),totalActual:items.reduce((s:number,x:any)=>s+x.actual,0)}}
 private title(value:string){return value.charAt(0)+value.slice(1).toLowerCase()}
}
