import { useMemo, useState } from 'react'
import PageHeader from '../../components/PageHeader/PageHeader'
import { useApp } from '../../context/AppContext'
import type { AuditEvent } from '../../types'
import './AuditLog.css'

const modules=['All modules','Students','Fees','Payments','Expenses','Budgets','Team','System']
export default function AuditLog(){
 const {auditEvents}=useApp();const [query,setQuery]=useState('');const [module,setModule]=useState('All modules');const [severity,setSeverity]=useState('All activity');const [selected,setSelected]=useState<AuditEvent|null>(null)
 const filtered=useMemo(()=>auditEvents.filter(event=>(`${event.action} ${event.description} ${event.user} ${event.recordId}`).toLowerCase().includes(query.toLowerCase())&&(module==='All modules'||event.module===module)&&(severity==='All activity'||event.severity===severity)),[auditEvents,query,module,severity]);const today=auditEvents.filter(e=>e.timestamp.includes('08 Aug 2026')).length;const critical=auditEvents.filter(e=>e.severity==='Critical').length;const users=new Set(auditEvents.map(e=>e.user)).size
 const exportLog=()=>{const rows=[['Event ID','Timestamp','User','Role','Action','Module','Record','Severity','Description'],...filtered.map(e=>[e.id,e.timestamp,e.user,e.role,e.action,e.module,e.recordId,e.severity,e.description])];const blob=new Blob([rows.map(row=>row.map(cell=>`"${cell}"`).join(',')).join('\n')],{type:'text/csv'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download='greenfield-audit-log.csv';anchor.click();URL.revokeObjectURL(url)}
 return <div className="audit-page"><PageHeader eyebrow="GOVERNANCE & COMPLIANCE" title="Audit log" subtitle="A tamper-evident trail of financial and administrative activity." actions={<button className="button button--primary" onClick={exportLog}><span className="material-symbols-rounded">download</span>Export audit log</button>}/>
 <section className="audit-notice"><span className="material-symbols-rounded">verified_user</span><div><b>Audit protection enabled</b><p>Events are retained as immutable records. Corrections create new entries instead of changing history.</p></div><span>POLICY ACTIVE</span></section>
 <section className="audit-summary"><article><span className="material-symbols-rounded">history</span><div><small>Total events</small><strong>{auditEvents.length}</strong><p>All recorded activity</p></div></article><article><span className="material-symbols-rounded">today</span><div><small>Events today</small><strong>{today}</strong><p>08 August 2026</p></div></article><article><span className="material-symbols-rounded">group</span><div><small>Active users</small><strong>{users}</strong><p>Staff and system actors</p></div></article><article className={critical?'critical':''}><span className="material-symbols-rounded">gpp_maybe</span><div><small>Critical events</small><strong>{critical}</strong><p>Requires audit review</p></div></article></section>
 <section className="audit-register"><div className="audit-tools"><div className="students-search"><span className="material-symbols-rounded">search</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search actions, users, records or descriptions"/></div><select value={module} onChange={e=>setModule(e.target.value)}>{modules.map(m=><option key={m}>{m}</option>)}</select><select value={severity} onChange={e=>setSeverity(e.target.value)}><option>All activity</option><option>Info</option><option>Success</option><option>Warning</option><option>Critical</option></select><button className="button button--light"><span className="material-symbols-rounded">date_range</span>Date range</button></div><div className="audit-timeline">{filtered.map((event,index)=><article className="audit-event" key={event.id} onClick={()=>setSelected(event)}><div className={`event-marker severity-${event.severity.toLowerCase()}`}><span className="material-symbols-rounded">{event.severity==='Critical'?'report':event.severity==='Warning'?'warning':event.severity==='Success'?'check_circle':'info'}</span>{index<filtered.length-1&&<i/>}</div><div className="event-main"><div className="event-head"><div><h3>{event.action}</h3><span className={`severity-tag ${event.severity.toLowerCase()}`}>{event.severity}</span></div><time>{event.timestamp}</time></div><p>{event.description}</p><div className="event-meta"><span><i className="user-initial">{event.user.split(' ').map(n=>n[0]).join('').slice(0,2)}</i><b>{event.user}</b> · {event.role}</span><span><span className="material-symbols-rounded">category</span>{event.module}</span><span><span className="material-symbols-rounded">tag</span>{event.recordId}</span>{event.changes&&<span className="changes-count"><span className="material-symbols-rounded">difference</span>{event.changes.length} change{event.changes.length!==1?'s':''}</span>}</div></div><button className="event-open"><span className="material-symbols-rounded">chevron_right</span></button></article>)}{!filtered.length&&<div className="empty-state"><span className="material-symbols-rounded">manage_search</span><p>No audit events match these filters.</p></div>}</div><div className="audit-footer"><span>Showing {filtered.length} of {auditEvents.length} immutable events</span><div><span className="material-symbols-rounded">lock</span>Retention period: 7 years</div></div></section>
 {selected&&<div className="audit-drawer"><div className="audit-backdrop" onClick={()=>setSelected(null)}/><section><header><div><span>AUDIT EVENT</span><h2>{selected.id}</h2><p>{selected.timestamp}</p></div><button onClick={()=>setSelected(null)}><span className="material-symbols-rounded">close</span></button></header><div className="audit-detail-body"><div className={`audit-detail-status ${selected.severity.toLowerCase()}`}><span className="material-symbols-rounded">{selected.severity==='Critical'?'gpp_maybe':'verified'}</span><div><b>{selected.action}</b><small>{selected.severity} activity · {selected.module}</small></div></div><div className="audit-description"><span>EVENT DESCRIPTION</span><p>{selected.description}</p></div><dl><div><dt>Performed by</dt><dd>{selected.user}</dd></div><div><dt>Role</dt><dd>{selected.role}</dd></div><div><dt>Affected record</dt><dd>{selected.recordId}</dd></div><div><dt>Module</dt><dd>{selected.module}</dd></div><div><dt>IP address</dt><dd>{selected.ipAddress||'192.168.1.24'}</dd></div><div><dt>Event timestamp</dt><dd>{selected.timestamp}</dd></div></dl>{selected.changes&&<div className="change-panel"><h3>Recorded changes</h3>{selected.changes.map((change,index)=><div className="change-row" key={`${change.field}-${index}`}><b>{change.field}</b><div><span>{change.before}</span><span className="material-symbols-rounded">arrow_forward</span><strong>{change.after}</strong></div></div>)}</div>}<div className="integrity-card"><span className="material-symbols-rounded">fingerprint</span><div><b>Integrity verified</b><small>This event has not been modified since creation.</small><code>SHA-256 · 8f2a…{selected.id.slice(-5).toLowerCase()}</code></div></div></div><footer><button className="button button--light" onClick={()=>window.print()}><span className="material-symbols-rounded">print</span>Print event</button><button className="button button--primary" onClick={()=>setSelected(null)}>Close</button></footer></section></div>}</div>
}
