import { useMemo, useState } from 'react'
import Swal from 'sweetalert2'
import PageHeader from '../../components/PageHeader/PageHeader'
import StatusBadge from '../../components/StatusBadge/StatusBadge'
import { useApp } from '../../context/AppContext'
import type { FeeItem, FeeStructure } from '../../types'
import { formatKES } from '../../utils/formatters'
import './FeeStructures.css'

const blankStructure=(termId:string,classId:string):FeeStructure=>({id:`FS-${Date.now()}`,name:'',grade:'',termId,term:'',year:2026,classIds:classId?[classId]:[],status:'Draft',updatedAt:new Date().toISOString(),items:[{id:`FI-${Date.now()}`,label:'Tuition',amount:0}]})

export default function FeeStructures(){
 const {feeStructures,invoiceBatches,students,academicClasses,academicYears,saveFeeStructure,generateInvoices}=useApp()
 const [tab,setTab]=useState<'structures'|'invoices'>('structures');const [editor,setEditor]=useState<FeeStructure|null>(null);const [query,setQuery]=useState('')
 const terms=academicYears.flatMap(year=>year.terms.map(term=>({...term,year:Number(year.name)})));const defaultTerm=terms.find(term=>term.status==='ACTIVE')||terms[0]
 const structures=useMemo(()=>feeStructures.filter(item=>(item.name+item.grade+item.term).toLowerCase().includes(query.toLowerCase())),[feeStructures,query])
 const active=feeStructures.filter(s=>s.status==='Active').length,totalExpected=invoiceBatches.reduce((sum,batch)=>sum+batch.total,0)
 const updateItem=(id:string,change:Partial<FeeItem>)=>setEditor(current=>current?{...current,items:current.items.map(item=>item.id===id?{...item,...change}:item)}:null)
 const save=async()=>{if(!editor)return;if(!editor.name.trim()||!editor.termId||!editor.classIds?.length||editor.items.some(item=>!item.label.trim()||item.amount<=0)){void Swal.fire({title:'Check fee details',text:'Add a name, term, assigned class, and valid fee items.',icon:'warning',confirmButtonColor:'#1f6b50'});return}try{const saved=await saveFeeStructure(editor);setEditor(null);void Swal.fire({title:'Fee structure saved',text:`${saved.name} is stored in the database.`,icon:'success',confirmButtonColor:'#1f6b50'})}catch(error){void Swal.fire({title:'Fee structure not saved',text:error instanceof Error?error.message:'The server rejected this structure.',icon:'error',confirmButtonColor:'#1f6b50'})}}
 const generate=(structure:FeeStructure)=>{const recipients=students.filter(student=>structure.classIds?.includes(student.classId||'')),total=structure.items.reduce((sum,item)=>sum+item.amount,0);void Swal.fire({title:'Generate student invoices?',html:`<div class="generate-confirm"><span>Fee structure</span><b>${structure.name}</b><span>Assigned classes</span><b>${structure.classes?.join(', ')||structure.grade}</b><span>Loaded recipients</span><b>${recipients.length}</b><span>Amount per student</span><b>${formatKES(total)}</b></div><p class="warning-copy">The server invoices every active matching enrolment exactly once for this generation key.</p>`,icon:'question',showCancelButton:true,confirmButtonText:'Generate invoices',confirmButtonColor:'#1f6b50',showLoaderOnConfirm:true,preConfirm:async()=>{try{return await generateInvoices(structure)}catch(error){Swal.showValidationMessage(error instanceof Error?error.message:'Invoices could not be generated')}}}).then(result=>{if(result.isConfirmed&&result.value){setTab('invoices');void Swal.fire({title:'Invoices generated',text:`${result.value.count} student invoices were created.`,icon:'success',confirmButtonColor:'#1f6b50'})}})}
 return <div className="fees-page"><PageHeader eyebrow="FEES & BILLING" title="Fee structures & invoices" subtitle="Define class charges and generate accurate student invoices." actions={<button className="button button--primary" disabled={!defaultTerm||!academicClasses.length} onClick={()=>setEditor(blankStructure(defaultTerm?.id||'',academicClasses[0]?.id||''))}><span className="material-symbols-rounded">add</span>New fee structure</button>}/>
 <section className="fees-summary"><article><div className="fees-summary__icon"><span className="material-symbols-rounded">contract</span></div><div><span>Fee structures</span><strong>{feeStructures.length}</strong><small>{active} active this term</small></div></article><article><div className="fees-summary__icon gold"><span className="material-symbols-rounded">receipt_long</span></div><div><span>Invoice batches</span><strong>{invoiceBatches.length}</strong><small>{invoiceBatches.reduce((sum,b)=>sum+b.count,0)} invoices generated</small></div></article><article><div className="fees-summary__icon blue"><span className="material-symbols-rounded">payments</span></div><div><span>Total invoiced</span><strong>{formatKES(totalExpected,true)}</strong><small>Across all active batches</small></div></article><article><div className="fees-summary__icon red"><span className="material-symbols-rounded">event</span></div><div><span>Current billing period</span><strong>{defaultTerm?.name||'Not configured'}</strong><small>{defaultTerm?`Ends ${new Date(defaultTerm.endsOn).toLocaleDateString()}`:'Create an active term'}</small></div></article></section>
 <div className="fees-tabs"><button className={tab==='structures'?'active':''} onClick={()=>setTab('structures')}><span className="material-symbols-rounded">view_list</span>Fee structures</button><button className={tab==='invoices'?'active':''} onClick={()=>setTab('invoices')}><span className="material-symbols-rounded">receipt</span>Invoice batches <i>{invoiceBatches.length}</i></button></div>
 {tab==='structures'?<section className="fees-panel"><div className="fees-toolbar"><div className="students-search"><span className="material-symbols-rounded">search</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search fee structures..."/></div></div><div className="structure-grid">{structures.map(structure=>{const total=structure.items.reduce((sum,item)=>sum+item.amount,0),assigned=students.filter(student=>structure.classIds?.includes(student.classId||'')).length;return <article className="structure-card" key={structure.id}><div className="structure-card__top"><div className="structure-card__icon"><span className="material-symbols-rounded">school</span></div><StatusBadge status={structure.status}/></div><span className="structure-card__term">{structure.term.toUpperCase()} • {structure.year}</span><h2>{structure.name}</h2><p>{structure.classes?.join(', ')||structure.grade} · {assigned} loaded students</p><div className="structure-total"><span>Total per student</span><strong>{formatKES(total)}</strong></div><div className="fee-preview">{structure.items.slice(0,3).map(item=><div key={item.id}><span>{item.label}</span><b>{formatKES(item.amount)}</b></div>)}</div><div className="structure-actions"><button onClick={()=>setEditor({...structure,classIds:[...(structure.classIds||[])]})}><span className="material-symbols-rounded">edit</span>Edit</button><button className="generate-button" disabled={structure.status!=='Active'} onClick={()=>generate(structure)}><span className="material-symbols-rounded">receipt_long</span>Generate invoices</button></div></article>})}</div></section>:<section className="fees-panel invoice-panel"><div className="invoice-panel__head"><div><h2>Invoice generation history</h2><p>Immutable batches generated from class assignments.</p></div></div><div className="table-wrap"><table><thead><tr><th>Batch reference</th><th>Fee structure</th><th>Billing period</th><th>Students</th><th>Total amount</th><th>Generated</th><th>Status</th></tr></thead><tbody>{invoiceBatches.map(batch=><tr key={batch.id}><td><strong>{batch.id.slice(0,12)}</strong></td><td><strong>{batch.structureName}</strong><small className="cell-small">{batch.grade}</small></td><td>{batch.term}</td><td>{batch.count}</td><td><strong>{formatKES(batch.total)}</strong></td><td>{new Date(batch.date).toLocaleDateString()}</td><td><StatusBadge status={batch.status}/></td></tr>)}</tbody></table></div></section>}
 {editor&&<div className="fee-modal" role="dialog" aria-modal="true"><div className="fee-modal__backdrop" onClick={()=>setEditor(null)}/><section className="fee-editor"><header><div><span>FEE STRUCTURE</span><h2>{feeStructures.some(s=>s.id===editor.id)?'Edit fee structure':'Create fee structure'}</h2><p>Define items and the class assignment.</p></div><button onClick={()=>setEditor(null)}><span className="material-symbols-rounded">close</span></button></header><div className="editor-body"><div className="editor-fields"><label>Structure name<input value={editor.name} onChange={e=>setEditor({...editor,name:e.target.value})}/></label><label>Assigned class<select value={editor.classIds?.[0]||''} onChange={e=>setEditor({...editor,classIds:[e.target.value]})}>{academicClasses.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Academic term<select value={editor.termId||''} onChange={e=>{const selected=terms.find(term=>term.id===e.target.value);setEditor({...editor,termId:e.target.value,term:selected?.name||'',year:selected?.year||editor.year})}}>{terms.map(term=><option value={term.id} key={term.id}>{term.name}, {term.year}</option>)}</select></label><label>Status<select value={editor.status} onChange={e=>setEditor({...editor,status:e.target.value as FeeStructure['status']})}><option>Draft</option><option>Active</option><option>Archived</option></select></label></div><div className="items-heading"><div><h3>Fee items</h3><p>Add every charge included in this structure.</p></div><button onClick={()=>setEditor({...editor,items:[...editor.items,{id:`FI-${Date.now()}`,label:'',amount:0}]})}><span className="material-symbols-rounded">add</span>Add item</button></div><div className="editor-items">{editor.items.map((item,index)=><div className="editor-item" key={item.id}><span>{String(index+1).padStart(2,'0')}</span><input value={item.label} onChange={e=>updateItem(item.id,{label:e.target.value})}/><div><span>KSh</span><input type="number" value={item.amount||''} onChange={e=>updateItem(item.id,{amount:Number(e.target.value)})}/></div><button disabled={editor.items.length===1} onClick={()=>setEditor({...editor,items:editor.items.filter(value=>value.id!==item.id)})}><span className="material-symbols-rounded">delete</span></button></div>)}</div><div className="editor-total"><div><span>Total fee per student</span><small>{editor.items.length} fee items</small></div><strong>{formatKES(editor.items.reduce((sum,item)=>sum+item.amount,0))}</strong></div></div><footer><button className="button button--light" onClick={()=>setEditor(null)}>Cancel</button><button className="button button--primary" onClick={()=>void save()}><span className="material-symbols-rounded">save</span>Save fee structure</button></footer></section></div>}</div>
}
