import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { useEffect, useState } from 'react'
import Swal from 'sweetalert2'
import PageHeader from '../../components/PageHeader/PageHeader'
import StatCard from '../../components/StatCard/StatCard'
import StatusBadge from '../../components/StatusBadge/StatusBadge'
import { classPerformance, collectionTrend, paymentMethods, payments, students as seedStudents } from '../../data/mockData'
import { useApp } from '../../context/AppContext'
import { formatKES } from '../../utils/formatters'
import { apiRequest } from '../../services/api'
import './Dashboard.css'

export default function Dashboard(){
 const {t,students}=useApp();const [live,setLive]=useState<{billed:number;collected:number;outstanding:number;expenses:number;collectionRate:number;overdueAccounts:number}|null>(null)
 useEffect(()=>{apiRequest<{summary:typeof live}>('/dashboard/summary').then(result=>setLive(result.summary)).catch(()=>setLive(null))},[])
 const initialBilled=seedStudents.reduce((sum,student)=>sum+student.billed,0);const currentBilled=students.reduce((sum,student)=>sum+student.billed,0)
 const initialPaid=seedStudents.reduce((sum,student)=>sum+student.paid,0);const currentPaid=students.reduce((sum,student)=>sum+student.paid,0)
 const expectedTotal=live?.billed??4_850_000+(currentBilled-initialBilled);const collectedTotal=live?.collected??3_920_000+(currentPaid-initialPaid);const outstandingTotal=live?.outstanding??expectedTotal-collectedTotal
 const paymentAlert=()=>Swal.fire({title:'Record a payment',html:'<p style="color:#687b74;font-size:13px">Payment entry will be connected to the student account in the Payments module.</p>',icon:'info',confirmButtonText:'Go to payments',confirmButtonColor:'#1f6b50'})
 return <div className="dashboard"><PageHeader eyebrow={t('term')} title={t('welcome')} subtitle={t('overviewSub')} actions={<><button className="button button--light"><span className="material-symbols-rounded">calendar_today</span>{t('term')}</button><button onClick={paymentAlert} className="button button--primary"><span className="material-symbols-rounded">add</span>{t('recordPayment')}</button></>}/>
 <section className="stats-grid"><StatCard label={t('expected')} value={formatKES(expectedTotal,true)} change="Live" icon="request_quote" tone="blue"/><StatCard label={t('collected')} value={formatKES(collectedTotal,true)} change={`${(live?.collectionRate||0).toFixed(1)}%`} icon="account_balance" tone="green"/><StatCard label={t('outstanding')} value={formatKES(outstandingTotal,true)} change={`${live?.overdueAccounts||0} overdue`} icon="schedule" tone="gold"/><StatCard label={t('expensesTotal')} value={formatKES(live?.expenses||0,true)} change="Approved" icon="receipt_long" tone="red"/></section>
 <section className="dashboard__middle"><article className="panel chart-panel"><div className="panel__head"><div><h2>{t('collections')}</h2><p>Monthly performance in KSh thousands</p></div><select aria-label="Chart period"><option>Last 6 months</option><option>This year</option></select></div><div className="chart-legend"><span><i className="green"/>Collected</span><span><i className="gold"/>Expenses</span></div><div className="area-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={collectionTrend} margin={{top:10,right:5,left:-25,bottom:0}}><defs><linearGradient id="greenFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#2a8062" stopOpacity=".25"/><stop offset="1" stopColor="#2a8062" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="#edf1ef" vertical={false}/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fontSize:10,fill:'#84918d'}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:9,fill:'#84918d'}}/><Tooltip formatter={(v)=>[`KSh ${v}K`]}/><Area type="monotone" dataKey="collected" stroke="#27785b" strokeWidth={2.5} fill="url(#greenFill)"/><Area type="monotone" dataKey="expenses" stroke="#d9a62e" strokeWidth={2} fill="transparent" strokeDasharray="5 4"/></AreaChart></ResponsiveContainer></div></article>
 <article className="panel collection-card"><div className="panel__head"><div><h2>{t('collectionRate')}</h2><p>{t('term')}</p></div><span className="material-symbols-rounded">more_horiz</span></div><div className="donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={[{value:80.8},{value:19.2}]} dataKey="value" innerRadius={57} outerRadius={70} startAngle={90} endAngle={-270} cornerRadius={5}><Cell fill="#23795b"/><Cell fill="#e9efec"/></Pie></PieChart></ResponsiveContainer><div><strong>80.8%</strong><span>collected</span></div></div><div className="collection-meta"><div><span>Collected</span><strong>KSh 3.92M</strong></div><div><span>Remaining</span><strong>KSh 930K</strong></div></div></article></section>
 <section className="dashboard__bottom"><article className="panel recent"><div className="panel__head"><div><h2>{t('recentPayments')}</h2><p>Latest fee transactions</p></div><button>{t('viewAll')} <span className="material-symbols-rounded">arrow_forward</span></button></div><div className="table-wrap"><table><thead><tr><th>Receipt</th><th>Student</th><th>Method</th><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody>{payments.slice(0,4).map(p=><tr key={p.id}><td><strong>{p.id}</strong></td><td><div className="student-cell"><span>{p.student.split(' ').map(n=>n[0]).join('')}</span><div><strong>{p.student}</strong><small>{p.admission}</small></div></div></td><td>{p.method}</td><td>{p.date}</td><td><strong>{formatKES(p.amount)}</strong></td><td><StatusBadge status={p.status}/></td></tr>)}</tbody></table></div></article>
 <article className="panel performance"><div className="panel__head"><div><h2>{t('classPerformance')}</h2><p>{t('term')}</p></div></div>{classPerformance.map(item=><div className="performance__row" key={item.grade}><div><strong>{item.grade}</strong><span>{item.amount}</span></div><div className="progress"><i style={{width:`${item.rate}%`}}/></div><b>{item.rate}%</b></div>)}<div className="methods"><h3>Payment methods</h3><div className="method-bar">{paymentMethods.map(m=><i key={m.name} style={{width:`${m.value}%`,background:m.color}}/>)}</div><div className="method-legend">{paymentMethods.map(m=><span key={m.name}><i style={{background:m.color}}/>{m.name} <b>{m.value}%</b></span>)}</div></div></article></section>
 </div>
}
