import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common'
import { Prisma, TransactionStatus } from '@shulefinance/database'
import type { AuthenticatedUser, RequestContext } from '../auth/auth.types'
import { DatabaseService } from '../database/database.service'
import { CapturePaymentDto, CreateReconciliationDto, PaymentListQueryDto, ReversePaymentDto } from './dto/payments.dto'

const paymentInclude={allocations:{include:{invoice:true,student:true}},reversedPayment:true,reversal:true} as const
const invoiceInclude={items:true,creditNotes:{include:{items:true}},adjustments:true,allocations:{include:{payment:true}}} as const

@Injectable()
export class PaymentsService{
 constructor(private readonly database:DatabaseService){}

 async list(user:AuthenticatedUser,query:PaymentListQueryDto){const where:Prisma.PaymentWhereInput={schoolId:user.schoolId,reversedPaymentId:null,...(query.method?{method:query.method}:{}),...(query.status?{status:query.status}:{}),...(query.search?{OR:[{receiptNumber:{contains:query.search,mode:'insensitive'}},{reference:{contains:query.search,mode:'insensitive'}},{allocations:{some:{student:{OR:[{firstName:{contains:query.search,mode:'insensitive'}},{lastName:{contains:query.search,mode:'insensitive'}},{admissionNumber:{contains:query.search,mode:'insensitive'}}]}}}}]}:{})};const [rows,total]=await this.database.$transaction([this.database.payment.findMany({where,include:paymentInclude,orderBy:{receivedAt:'desc'},skip:(query.page-1)*query.pageSize,take:query.pageSize}),this.database.payment.count({where})]);return{payments:rows.map(row=>this.present(row)),pagination:{page:query.page,pageSize:query.pageSize,total,totalPages:Math.ceil(total/query.pageSize)}}}

 async capture(user:AuthenticatedUser,dto:CapturePaymentDto,context:RequestContext){const key=dto.idempotencyKey.trim();const existing=await this.database.payment.findUnique({where:{schoolId_idempotencyKey:{schoolId:user.schoolId,idempotencyKey:key}},include:paymentInclude});if(existing)return{payment:this.present(existing),idempotentReplay:true};const student=await this.database.student.findFirst({where:{id:dto.studentId,schoolId:user.schoolId}});if(!student)throw new NotFoundException('Student not found');const reference=dto.reference.trim().toUpperCase();try{const payment=await this.database.$transaction(async tx=>{const invoices=await tx.invoice.findMany({where:{schoolId:user.schoolId,studentId:dto.studentId,status:'ACTIVE'},include:invoiceInclude,orderBy:{issuedAt:'asc'}});const requested=dto.allocations?this.explicitAllocations(dto.allocations,invoices):this.autoAllocations(dto.amount,invoices);const allocated=requested.reduce((sum,row)=>sum+row.amount,0);if(Math.abs(allocated-dto.amount)>0.001)throw new BadRequestException(`Payment must be fully allocated. Available invoice balance is KSh ${allocated.toLocaleString()}.`);const receiptNumber=await this.nextReceipt(tx,user.schoolId);const row=await tx.payment.create({data:{schoolId:user.schoolId,receiptNumber,method:dto.method,reference,amount:dto.amount,idempotencyKey:key,receivedAt:dto.receivedAt?new Date(dto.receivedAt):undefined,allocations:{create:requested.map(item=>({invoiceId:item.invoiceId,studentId:dto.studentId,amount:item.amount}))}}});await tx.auditEvent.create({data:{schoolId:user.schoolId,actorId:user.id,action:'PAYMENT_CAPTURED',module:'Payments',recordType:'Payment',recordId:row.id,after:{receiptNumber,studentId:dto.studentId,amount:dto.amount,method:dto.method,reference,allocations:requested},ipAddress:context.ipAddress,requestId:context.requestId}});return tx.payment.findUniqueOrThrow({where:{id:row.id},include:paymentInclude})},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});return{payment:this.present(payment),idempotentReplay:false}}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002'){const replay=await this.database.payment.findUnique({where:{schoolId_idempotencyKey:{schoolId:user.schoolId,idempotencyKey:key}},include:paymentInclude});if(replay)return{payment:this.present(replay),idempotentReplay:true};throw new ConflictException('This payment reference already exists')}throw error}}

 async receipt(user:AuthenticatedUser,id:string){const payment=await this.database.payment.findFirst({where:{id,schoolId:user.schoolId},include:{...paymentInclude,school:{include:{settings:true}}}});if(!payment)throw new NotFoundException('Payment not found');return{receipt:this.presentReceipt(payment)}}

 async reverse(user:AuthenticatedUser,id:string,dto:ReversePaymentDto,context:RequestContext){const replay=await this.database.payment.findUnique({where:{schoolId_idempotencyKey:{schoolId:user.schoolId,idempotencyKey:dto.idempotencyKey}},include:paymentInclude});if(replay)return{payment:this.present(replay),idempotentReplay:true};const original=await this.database.payment.findFirst({where:{id,schoolId:user.schoolId},include:paymentInclude});if(!original)throw new NotFoundException('Payment not found');if(original.status!=='COMPLETED'||original.reversedPaymentId)throw new ConflictException('Only unreversed completed payments can be reversed');const reversal=await this.database.$transaction(async tx=>{const receiptNumber=await this.nextReceipt(tx,user.schoolId);await tx.payment.update({where:{id},data:{status:TransactionStatus.VOIDED,reversalReason:dto.reason.trim(),reversedAt:new Date()}});const row=await tx.payment.create({data:{schoolId:user.schoolId,receiptNumber,method:original.method,reference:`REV-${original.reference}-${id.slice(0,8)}`,amount:original.amount,status:TransactionStatus.COMPLETED,reversedPaymentId:id,idempotencyKey:dto.idempotencyKey,reversalReason:dto.reason.trim()}});await tx.auditEvent.create({data:{schoolId:user.schoolId,actorId:user.id,action:'PAYMENT_REVERSED',module:'Payments',recordType:'Payment',recordId:id,before:{status:'COMPLETED',amount:Number(original.amount)},after:{status:'VOIDED',reversalId:row.id,reason:dto.reason},ipAddress:context.ipAddress,requestId:context.requestId}});return tx.payment.findUniqueOrThrow({where:{id},include:paymentInclude})},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});return{payment:this.present(reversal),idempotentReplay:false}}

 async reconcile(user:AuthenticatedUser,dto:CreateReconciliationDto,context:RequestContext){if(new Date(dto.periodStart)>new Date(dto.periodEnd))throw new BadRequestException('Period start must be before period end');const refs=dto.entries.map(item=>item.reference.trim().toUpperCase());if(new Set(refs).size!==refs.length)throw new BadRequestException('Statement references must be unique');const payments=await this.database.payment.findMany({where:{schoolId:user.schoolId,reference:{in:refs},receivedAt:{gte:new Date(dto.periodStart),lte:new Date(`${dto.periodEnd.slice(0,10)}T23:59:59.999Z`)}}});const byReference=new Map(payments.map(row=>[row.reference.toUpperCase(),row]));const items=dto.entries.map(entry=>{const payment=byReference.get(entry.reference.trim().toUpperCase());const status=!payment?'MISSING_PAYMENT':Math.abs(Number(payment.amount)-entry.amount)>0.001?'AMOUNT_MISMATCH':'MATCHED';return{paymentId:payment?.id,externalReference:entry.reference.trim().toUpperCase(),externalAmount:entry.amount,status} as const});const statementTotal=dto.entries.reduce((sum,row)=>sum+row.amount,0);const matchedTotal=items.filter(row=>row.status==='MATCHED').reduce((sum,row)=>sum+Number(byReference.get(row.externalReference)?.amount||0),0);const status=items.every(row=>row.status==='MATCHED')?'MATCHED':'DISCREPANCY';const created=await this.database.$transaction(async tx=>{const row=await tx.paymentReconciliation.create({data:{schoolId:user.schoolId,name:dto.name.trim(),periodStart:new Date(dto.periodStart),periodEnd:new Date(dto.periodEnd),status,statementTotal,matchedTotal,items:{create:items}}});await tx.auditEvent.create({data:{schoolId:user.schoolId,actorId:user.id,action:'PAYMENTS_RECONCILED',module:'Payments',recordType:'PaymentReconciliation',recordId:row.id,after:{status,statementTotal,matchedTotal,itemCount:items.length},ipAddress:context.ipAddress,requestId:context.requestId}});return tx.paymentReconciliation.findUniqueOrThrow({where:{id:row.id},include:{items:true}})});return{reconciliation:this.presentReconciliation(created)}}
 async listReconciliations(user:AuthenticatedUser){const rows=await this.database.paymentReconciliation.findMany({where:{schoolId:user.schoolId},include:{items:true},orderBy:{createdAt:'desc'},take:50});return{reconciliations:rows.map(row=>this.presentReconciliation(row))}}

 private invoiceBalance(invoice:any){const items=invoice.items.reduce((s:number,x:any)=>s+Number(x.amount),0);const debits=invoice.adjustments.filter((x:any)=>x.type==='DEBIT').reduce((s:number,x:any)=>s+Number(x.amount),0);const credits=invoice.adjustments.filter((x:any)=>x.type==='CREDIT').reduce((s:number,x:any)=>s+Number(x.amount),0)+invoice.creditNotes.filter((x:any)=>x.status==='ACTIVE').flatMap((x:any)=>x.items).reduce((s:number,x:any)=>s+Number(x.amount),0);const paid=invoice.allocations.filter((x:any)=>x.payment.status==='COMPLETED').reduce((s:number,x:any)=>s+Number(x.amount),0);return Math.max(0,items+debits-credits-paid)}
 private explicitAllocations(requested:{invoiceId:string;amount:number}[],invoices:any[]){if(new Set(requested.map(row=>row.invoiceId)).size!==requested.length)throw new BadRequestException('Each invoice can only appear once');return requested.map(row=>{const invoice=invoices.find(item=>item.id===row.invoiceId);if(!invoice)throw new BadRequestException('An allocated invoice is unavailable for this student');if(row.amount-this.invoiceBalance(invoice)>0.001)throw new BadRequestException(`Allocation exceeds the balance on ${invoice.invoiceNumber}`);return row})}
 private autoAllocations(amount:number,invoices:any[]){let remaining=amount;const rows:{invoiceId:string;amount:number}[]=[];for(const invoice of invoices){const balance=this.invoiceBalance(invoice);if(balance<=0)continue;const allocated=Math.min(balance,remaining);rows.push({invoiceId:invoice.id,amount:allocated});remaining-=allocated;if(remaining<0.001)break}return rows}
 private async nextReceipt(tx:Prisma.TransactionClient,schoolId:string){const [settings,sequence]=await Promise.all([tx.schoolSetting.findUnique({where:{schoolId}}),tx.receiptSequence.upsert({where:{schoolId},create:{schoolId,lastNumber:1},update:{lastNumber:{increment:1}}})]);return`${settings?.receiptPrefix||'RCT'}-${new Date().getFullYear()}-${String(sequence.lastNumber).padStart(6,'0')}`}
 private present(row:any){const student=row.allocations[0]?.student;return{id:row.id,receiptNumber:row.receiptNumber,studentId:student?.id||null,student:student?{id:student.id,name:`${student.firstName} ${student.lastName}`,admissionNumber:student.admissionNumber}:null,method:row.method,reference:row.reference,amount:Number(row.amount),status:row.status,receivedAt:row.receivedAt,reversalReason:row.reversalReason,reversalId:row.reversal?.id||null,reversedPaymentId:row.reversedPaymentId,allocations:row.allocations.map((item:any)=>({id:item.id,invoiceId:item.invoiceId,invoiceNumber:item.invoice.invoiceNumber,amount:Number(item.amount)}))}}
 private presentReceipt(row:any){return{...this.present(row),school:{name:row.school.name,registrationNumber:row.school.registrationNumber,currency:row.school.currency},issuedAt:new Date().toISOString()}}
 private presentReconciliation(row:any){return{id:row.id,name:row.name,periodStart:row.periodStart,periodEnd:row.periodEnd,status:row.status,statementTotal:Number(row.statementTotal),matchedTotal:Number(row.matchedTotal),createdAt:row.createdAt,items:row.items.map((item:any)=>({id:item.id,paymentId:item.paymentId,reference:item.externalReference,amount:Number(item.externalAmount),status:item.status}))}}
}
