import { useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import Swal from 'sweetalert2'
import StatusBadge from '../../components/StatusBadge/StatusBadge'
import { useApp } from '../../context/AppContext'
import { feeItemsByGrade } from '../../data/mockData'
import { formatKES } from '../../utils/formatters'
import './StudentDetail.css'

export default function StudentDetail(){
 const {studentId}=useParams();const navigate=useNavigate();const {students,transactions,feeStructures,recordPayment,updateStudent}=useApp();const student=students.find(s=>s.id===studentId);const [tab,setTab]=useState<'statement'|'invoices'|'guardian'>('statement')
 if(!student)return <div className="not-found"><span className="material-symbols-rounded">person_off</span><h2>Student not found</h2><Link to="/students">Return to students</Link></div>
 const balance=student.billed-student.paid;const progress=Math.round(student.paid/student.billed*100);const studentTransactions=transactions.filter(t=>t.studentId===student.id);const assignedStructure=feeStructures.find(structure=>structure.status==='Active'&&student.grade.startsWith(structure.grade));const feeItems=assignedStructure?.items||feeItemsByGrade[student.grade]||[{id:'F-01',label:'Tuition',amount:25000},{id:'F-02',label:'Meals & activities',amount:student.billed-25000}]
 const payment=()=>Swal.fire({title:'Record fee payment',html:`<div class="payment-student"><b>${student.name}</b><span>Balance: ${formatKES(balance)}</span></div><input id="pay-amount" type="number" class="swal2-input" placeholder="Amount in KSh" max="${balance}"><select id="pay-method" class="swal2-select"><option>M-Pesa</option><option>Bank</option><option>Cash</option><option>Cheque</option></select><input id="pay-ref" class="swal2-input" placeholder="Transaction reference">`,showCancelButton:true,confirmButtonText:'Post payment',confirmButtonColor:'#1f6b50',preConfirm:()=>{const amount=Number((document.getElementById('pay-amount') as HTMLInputElement).value);const method=(document.getElementById('pay-method') as HTMLSelectElement).value;const reference=(document.getElementById('pay-ref') as HTMLInputElement).value;if(!amount||amount<=0||amount>balance){Swal.showValidationMessage(`Enter an amount between KSh 1 and ${formatKES(balance)}`);return false}if(!reference){Swal.showValidationMessage('A transaction reference is required');return false}return{amount,method,reference}}}).then(result=>{if(result.isConfirmed&&result.value){const receipt=recordPayment(student.id,result.value.amount,result.value.method,result.value.reference);Swal.fire({title:'Payment posted',html:`<div class="receipt-success"><span>Receipt number</span><b>${receipt.id}</b><span>Amount received</span><b>${formatKES(receipt.amount)}</b></div>`,icon:'success',confirmButtonText:'Done',confirmButtonColor:'#1f6b50'})}})
 const edit=()=>Swal.fire({title:'Edit student details',html:`<input id="edit-name" class="swal2-input" value="${student.name}"><input id="edit-guardian" class="swal2-input" value="${student.guardian}"><input id="edit-phone" class="swal2-input" value="${student.phone}">`,showCancelButton:true,confirmButtonText:'Save changes',confirmButtonColor:'#1f6b50',preConfirm:()=>({name:(document.getElementById('edit-name') as HTMLInputElement).value,guardian:(document.getElementById('edit-guardian') as HTMLInputElement).value,phone:(document.getElementById('edit-phone') as HTMLInputElement).value})}).then(result=>{if(result.isConfirmed&&result.value){updateStudent({...student,...result.value});Swal.fire({title:'Changes saved',icon:'success',confirmButtonColor:'#1f6b50'})}})
 const printStatement=()=>window.print()
 return <div className="student-detail"><div className="detail-breadcrumb"><button onClick={()=>navigate('/students')}><span className="material-symbols-rounded">arrow_back</span></button><Link to="/students">Students</Link><span>/</span><b>{student.name}</b></div>
 <section className="profile-banner"><div className="profile-avatar" style={{background:student.color}}>{student.initials}</div><div className="profile-heading"><div><h1>{student.name}</h1><StatusBadge status={student.status}/></div><p><span className="material-symbols-rounded">badge</span>{student.admission}<i/> <span className="material-symbols-rounded">school</span>{student.grade}</p></div><div className="profile-actions"><button className="button button--light" onClick={edit}><span className="material-symbols-rounded">edit</span>Edit details</button><button className="button button--primary" onClick={payment} disabled={balance<=0}><span className="material-symbols-rounded">add_card</span>Record payment</button></div></section>
 <section className="account-cards"><article><span>Total billed</span><strong>{formatKES(student.billed)}</strong><small>Term 2, 2026</small></article><article className="account-card--green"><span>Amount paid</span><strong>{formatKES(student.paid)}</strong><small>{progress}% of fees cleared</small></article><article className={balance?'account-card--red':'account-card--green'}><span>Outstanding balance</span><strong>{formatKES(balance)}</strong><small>{balance?'Due by 30 Aug 2026':'Account fully settled'}</small></article><article className="progress-card"><div><span>Payment progress</span><b>{progress}%</b></div><div className="detail-progress"><i style={{width:`${progress}%`}}/></div><small>{formatKES(balance)} remaining</small></article></section>
 <div className="detail-layout"><main className="detail-main"><div className="detail-tabs"><button className={tab==='statement'?'active':''} onClick={()=>setTab('statement')}>Account statement</button><button className={tab==='invoices'?'active':''} onClick={()=>setTab('invoices')}>Fee breakdown</button><button className={tab==='guardian'?'active':''} onClick={()=>setTab('guardian')}>Guardian details</button></div>
 {tab==='statement'&&<section className="detail-panel"><div className="detail-panel__head"><div><h2>Transaction history</h2><p>All charges and payments for Term 2</p></div><button onClick={printStatement}><span className="material-symbols-rounded">print</span>Print statement</button></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Reference</th><th>Description</th><th>Debit</th><th>Credit</th><th>Status</th></tr></thead><tbody>{studentTransactions.map(row=><tr key={row.id}><td>{row.date}</td><td><strong>{row.id}</strong>{row.reference&&<small className="cell-small">{row.reference}</small>}</td><td>{row.description}{row.method&&<small className="cell-small">via {row.method}</small>}</td><td>{row.type==='Invoice'?formatKES(row.amount):'—'}</td><td className="paid-amount">{row.type==='Payment'?formatKES(row.amount):'—'}</td><td><StatusBadge status={row.status}/></td></tr>)}</tbody></table>{!studentTransactions.length&&<div className="empty-state"><span className="material-symbols-rounded">receipt_long</span><p>No transactions recorded yet.</p></div>}</div></section>}
 {tab==='invoices'&&<section className="detail-panel fee-breakdown"><div className="detail-panel__head"><div><h2>Term 2 fee breakdown</h2><p>Assigned from {student.grade} fee structure</p></div><span className="invoice-number">INV-2026-{student.admission.slice(-3)}</span></div>{feeItems.map(item=><div className="fee-line" key={item.id}><div><span className="material-symbols-rounded">check_circle</span><b>{item.label}</b></div><strong>{formatKES(item.amount)}</strong></div>)}<div className="fee-total"><span>Total invoiced</span><strong>{formatKES(student.billed)}</strong></div></section>}
 {tab==='guardian'&&<section className="detail-panel guardian-panel"><div className="guardian-avatar">{student.guardian.split(' ').map(n=>n[0]).join('')}</div><div><span>Primary guardian</span><h2>{student.guardian}</h2><p><span className="material-symbols-rounded">call</span>{student.phone}</p><p><span className="material-symbols-rounded">mail</span>{student.guardian.toLowerCase().replace(' ','.')}@example.com</p></div><button className="button button--light" onClick={()=>Swal.fire({title:'Reminder queued',text:`A fee balance reminder will be sent to ${student.guardian}.`,icon:'success',confirmButtonColor:'#1f6b50'})}><span className="material-symbols-rounded">notifications_active</span>Send fee reminder</button></section>}</main>
 <aside className="detail-side"><section><h3>Account information</h3><dl><div><dt>Academic term</dt><dd>Term 2, 2026</dd></div><div><dt>Fee structure</dt><dd>{student.grade} — Standard</dd></div><div><dt>Account status</dt><dd><StatusBadge status={student.status}/></dd></div><div><dt>Next due date</dt><dd>30 Aug 2026</dd></div></dl></section><section className="note-card"><div><span className="material-symbols-rounded">sticky_note_2</span><h3>Internal note</h3></div><p>Guardian requested payment reminders by SMS two days before the due date.</p><button onClick={()=>Swal.fire({title:'Add account note',input:'textarea',inputPlaceholder:'Write a private note for finance staff...',showCancelButton:true,confirmButtonText:'Save note',confirmButtonColor:'#1f6b50'})}>Edit note</button></section></aside></div></div>
}
