import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common'
import { Prisma, RecordStatus } from '@shulefinance/database'
import { randomUUID } from 'node:crypto'
import type { AuthenticatedUser, RequestContext } from '../auth/auth.types'
import { DatabaseService } from '../database/database.service'
import type { ChangeInvoiceStateDto, CreateAdjustmentDto, CreateCreditNoteDto, FeeListQueryDto, GenerateInvoicesDto, InvoiceListQueryDto, SaveFeeStructureDto } from './dto/fees.dto'

const structureInclude=Prisma.validator<Prisma.FeeStructureInclude>()({items:true,assignments:{include:{class:true}},term:{include:{academicYear:true}},_count:{select:{batches:true}}})
const invoiceInclude=Prisma.validator<Prisma.InvoiceInclude>()({student:true,term:{include:{academicYear:true}},items:true,allocations:{include:{payment:true}},creditNotes:{where:{status:'ACTIVE'},include:{items:true}},adjustments:true})
type StructureRecord=Prisma.FeeStructureGetPayload<{include:typeof structureInclude}>
type InvoiceRecord=Prisma.InvoiceGetPayload<{include:typeof invoiceInclude}>

@Injectable()
export class FeesService{
 constructor(private readonly database:DatabaseService){}
 async listStructures(user:AuthenticatedUser,query:FeeListQueryDto){const rows=await this.database.feeStructure.findMany({where:{schoolId:user.schoolId,...(query.termId?{termId:query.termId}:{}),...(query.status?{status:query.status}:{}),...(query.search?{name:{contains:query.search,mode:'insensitive'}}:{})},include:structureInclude,orderBy:{updatedAt:'desc'}});return{feeStructures:rows.map(row=>this.presentStructure(row))}}
 async createStructure(user:AuthenticatedUser,dto:SaveFeeStructureDto,context:RequestContext){await this.validateAcademicLinks(user.schoolId,dto.termId,dto.classIds);const created=await this.database.$transaction(async tx=>{const row=await tx.feeStructure.create({data:{schoolId:user.schoolId,termId:dto.termId,name:dto.name.trim(),status:dto.status,items:{create:dto.items.map(item=>({name:item.label.trim(),amount:item.amount}))},assignments:{create:[...new Set(dto.classIds)].map(classId=>({classId}))}}});await tx.auditEvent.create({data:{schoolId:user.schoolId,actorId:user.id,action:'FEE_STRUCTURE_CREATED',module:'Fees',recordType:'FeeStructure',recordId:row.id,after:{name:dto.name,termId:dto.termId,classIds:[...dto.classIds],items:dto.items.map(item=>({label:item.label,amount:item.amount}))},ipAddress:context.ipAddress,requestId:context.requestId}});return tx.feeStructure.findUniqueOrThrow({where:{id:row.id},include:structureInclude})});return{feeStructure:this.presentStructure(created)}}
 async updateStructure(user:AuthenticatedUser,id:string,dto:SaveFeeStructureDto,context:RequestContext){const current=await this.database.feeStructure.findFirst({where:{id,schoolId:user.schoolId},include:structureInclude});if(!current)throw new NotFoundException('Fee structure not found');if(current.status==='ARCHIVED')throw new ConflictException('Archived fee structures cannot be changed');await this.validateAcademicLinks(user.schoolId,dto.termId,dto.classIds);const updated=await this.database.$transaction(async tx=>{await tx.feeStructureItem.deleteMany({where:{feeStructureId:id}});await tx.feeStructureAssignment.deleteMany({where:{feeStructureId:id}});await tx.feeStructure.update({where:{id},data:{name:dto.name.trim(),termId:dto.termId,status:dto.status,items:{create:dto.items.map(item=>({name:item.label.trim(),amount:item.amount}))},assignments:{create:[...new Set(dto.classIds)].map(classId=>({classId}))}}});await tx.auditEvent.create({data:{schoolId:user.schoolId,actorId:user.id,action:'FEE_STRUCTURE_UPDATED',module:'Fees',recordType:'FeeStructure',recordId:id,before:{name:current.name,status:current.status,items:current.items.map(item=>({name:item.name,amount:Number(item.amount)})),classIds:current.assignments.map(item=>item.classId)},after:{name:dto.name,status:dto.status,items:dto.items.map(item=>({label:item.label,amount:item.amount})),classIds:[...dto.classIds]},ipAddress:context.ipAddress,requestId:context.requestId}});return tx.feeStructure.findUniqueOrThrow({where:{id},include:structureInclude})});return{feeStructure:this.presentStructure(updated)}}
 async generateBatch(user:AuthenticatedUser,structureId:string,dto:GenerateInvoicesDto,context:RequestContext){const existing=await this.database.invoiceBatch.findUnique({where:{schoolId_idempotencyKey:{schoolId:user.schoolId,idempotencyKey:dto.idempotencyKey}},include:{feeStructure:{include:structureInclude},invoices:{include:{items:true}}}});if(existing)return{batch:this.presentBatch(existing),idempotentReplay:true};const structure=await this.database.feeStructure.findFirst({where:{id:structureId,schoolId:user.schoolId},include:structureInclude});if(!structure)throw new NotFoundException('Fee structure not found');if(structure.status!=='ACTIVE')throw new ConflictException('Only active fee structures can generate invoices');const classIds=structure.assignments.map(item=>item.classId);if(!classIds.length)throw new BadRequestException('Assign at least one class before generating invoices');const enrolments=await this.database.enrolment.findMany({where:{termId:structure.termId,classId:{in:classIds},student:{schoolId:user.schoolId,status:'ACTIVE'}},include:{student:true}});if(!enrolments.length)throw new BadRequestException('No active enrolled students match this assignment');const batchId=randomUUID();const batch=await this.database.$transaction(async tx=>{const created=await tx.invoiceBatch.create({data:{id:batchId,schoolId:user.schoolId,feeStructureId:structure.id,idempotencyKey:dto.idempotencyKey}});for(const enrolment of enrolments){const invoiceNumber=`INV-${structure.term.academicYear.name}-${enrolment.student.admissionNumber}-${batchId.slice(0,8)}`;await tx.invoice.create({data:{schoolId:user.schoolId,studentId:enrolment.studentId,termId:structure.termId,batchId:created.id,invoiceNumber,status:'ACTIVE',dueAt:dto.dueAt?new Date(dto.dueAt):structure.term.endsOn,items:{create:structure.items.map(item=>({description:item.name,amount:item.amount}))}}})}await tx.auditEvent.create({data:{schoolId:user.schoolId,actorId:user.id,action:'INVOICE_BATCH_GENERATED',module:'Fees',recordType:'InvoiceBatch',recordId:created.id,after:{feeStructureId:structure.id,idempotencyKey:dto.idempotencyKey,invoiceCount:enrolments.length},ipAddress:context.ipAddress,requestId:context.requestId}});return tx.invoiceBatch.findUniqueOrThrow({where:{id:created.id},include:{feeStructure:{include:structureInclude},invoices:{include:{items:true}}}})});return{batch:this.presentBatch(batch),idempotentReplay:false}}
 async listBatches(user:AuthenticatedUser){const batches=await this.database.invoiceBatch.findMany({where:{schoolId:user.schoolId},include:{feeStructure:{include:structureInclude},invoices:{include:{items:true,allocations:{include:{payment:true}},creditNotes:{where:{status:'ACTIVE'},include:{items:true}},adjustments:true}}},orderBy:{createdAt:'desc'}});return{invoiceBatches:batches.map(row=>this.presentBatch(row))}}
 async listInvoices(user:AuthenticatedUser,query:InvoiceListQueryDto){const where:Prisma.InvoiceWhereInput={schoolId:user.schoolId,...(query.studentId?{studentId:query.studentId}:{}),...(query.status?{status:query.status}:{})};const [rows,total]=await this.database.$transaction([this.database.invoice.findMany({where,include:invoiceInclude,orderBy:{issuedAt:'desc'},skip:(query.page-1)*query.pageSize,take:query.pageSize}),this.database.invoice.count({where})]);return{invoices:rows.map(row=>this.presentInvoice(row)),pagination:{page:query.page,pageSize:query.pageSize,total,totalPages:Math.ceil(total/query.pageSize)}}}
 async changeInvoiceState(user:AuthenticatedUser,id:string,dto:ChangeInvoiceStateDto,context:RequestContext){const invoice=await this.findInvoice(user.schoolId,id);const allowed:Record<string,RecordStatus[]>={DRAFT:['ACTIVE','VOIDED'],ACTIVE:['ARCHIVED','VOIDED'],ARCHIVED:[],VOIDED:[]};if(!allowed[invoice.status]?.includes(dto.status))throw new ConflictException(`Cannot change invoice from ${invoice.status} to ${dto.status}`);if(dto.status==='VOIDED'&&(invoice.allocations.some(item=>item.payment.status==='COMPLETED')||invoice.creditNotes.length))throw new ConflictException('Invoices with payments or credit notes cannot be voided');const updated=await this.database.$transaction(async tx=>{const row=await tx.invoice.update({where:{id},data:{status:dto.status}});await tx.auditEvent.create({data:{schoolId:user.schoolId,actorId:user.id,action:'INVOICE_STATE_CHANGED',module:'Fees',recordType:'Invoice',recordId:id,before:{status:invoice.status},after:{status:dto.status},ipAddress:context.ipAddress,requestId:context.requestId}});return row});return{invoice:updated}}
 async createCreditNote(user:AuthenticatedUser,id:string,dto:CreateCreditNoteDto,context:RequestContext){const invoice=await this.findInvoice(user.schoolId,id);if(invoice.status!=='ACTIVE')throw new ConflictException('Credit notes require an active invoice');const gross=this.invoiceGross(invoice);if(dto.amount>gross)throw new BadRequestException('Credit cannot exceed the remaining adjusted invoice value');const number=`CRN-${new Date().getFullYear()}-${randomUUID().slice(0,8).toUpperCase()}`;const note=await this.database.$transaction(async tx=>{const row=await tx.creditNote.create({data:{schoolId:user.schoolId,studentId:invoice.studentId,invoiceId:id,creditNoteNumber:number,reason:dto.reason.trim(),items:{create:{description:dto.description.trim(),amount:dto.amount}}}});await tx.auditEvent.create({data:{schoolId:user.schoolId,actorId:user.id,action:'CREDIT_NOTE_ISSUED',module:'Fees',recordType:'CreditNote',recordId:row.id,after:{invoiceId:id,number,amount:dto.amount,reason:dto.reason},ipAddress:context.ipAddress,requestId:context.requestId}});return row});return{creditNote:note}}
 async createAdjustment(user:AuthenticatedUser,id:string,dto:CreateAdjustmentDto,context:RequestContext){const invoice=await this.findInvoice(user.schoolId,id);if(invoice.status!=='ACTIVE')throw new ConflictException('Adjustments require an active invoice');if(dto.type==='CREDIT'&&dto.amount>this.invoiceGross(invoice))throw new BadRequestException('Credit adjustment exceeds the remaining adjusted invoice value');const adjustment=await this.database.$transaction(async tx=>{const row=await tx.invoiceAdjustment.create({data:{schoolId:user.schoolId,invoiceId:id,type:dto.type,description:dto.description.trim(),amount:dto.amount}});await tx.auditEvent.create({data:{schoolId:user.schoolId,actorId:user.id,action:'INVOICE_ADJUSTMENT_CREATED',module:'Fees',recordType:'InvoiceAdjustment',recordId:row.id,after:{invoiceId:id,type:dto.type,amount:dto.amount,description:dto.description},ipAddress:context.ipAddress,requestId:context.requestId}});return row});return{adjustment}}
 async statement(user:AuthenticatedUser,studentId:string){const student=await this.database.student.findFirst({where:{id:studentId,schoolId:user.schoolId},include:{invoices:{include:invoiceInclude},paymentAllocations:{include:{payment:true,invoice:true}},creditNotes:{where:{status:'ACTIVE'},include:{items:true,invoice:true}}}});if(!student)throw new NotFoundException('Student not found');const lines=[...student.invoices.flatMap(invoice=>[{id:invoice.id,date:invoice.issuedAt,type:'Invoice',reference:invoice.invoiceNumber,description:`${invoice.term.name} invoice`,debit:invoice.items.reduce((s,i)=>s+Number(i.amount),0),credit:0,status:invoice.status},...invoice.adjustments.map(a=>({id:a.id,date:a.createdAt,type:'Adjustment',reference:invoice.invoiceNumber,description:a.description,debit:a.type==='DEBIT'?Number(a.amount):0,credit:a.type==='CREDIT'?Number(a.amount):0,status:'ACTIVE'}))]),...student.paymentAllocations.filter(a=>a.payment.status==='COMPLETED').map(a=>({id:a.id,date:a.payment.receivedAt,type:'Payment',reference:a.payment.receiptNumber,description:`Payment via ${a.payment.method}`,debit:0,credit:Number(a.amount),status:a.payment.status})),...student.creditNotes.map(note=>({id:note.id,date:note.issuedAt,type:'Credit note',reference:note.creditNoteNumber,description:note.reason,debit:0,credit:note.items.reduce((s,i)=>s+Number(i.amount),0),status:note.status}))].sort((a,b)=>a.date.getTime()-b.date.getTime());let balance=0;return{student:{id:student.id,name:`${student.firstName} ${student.lastName}`,admissionNumber:student.admissionNumber},lines:lines.map(line=>{balance+=line.debit-line.credit;return{...line,date:line.date.toISOString(),balance}}),summary:{debits:lines.reduce((s,l)=>s+l.debit,0),credits:lines.reduce((s,l)=>s+l.credit,0),balance}}}
 private async findInvoice(schoolId:string,id:string){const row=await this.database.invoice.findFirst({where:{id,schoolId},include:invoiceInclude});if(!row)throw new NotFoundException('Invoice not found');return row}
 private invoiceGross(invoice:InvoiceRecord){const charges=invoice.items.reduce((s,i)=>s+Number(i.amount),0)+invoice.adjustments.filter(a=>a.type==='DEBIT').reduce((s,a)=>s+Number(a.amount),0);const credits=invoice.creditNotes.flatMap(n=>n.items).reduce((s,i)=>s+Number(i.amount),0)+invoice.adjustments.filter(a=>a.type==='CREDIT').reduce((s,a)=>s+Number(a.amount),0);return Math.max(0,charges-credits)}
 private async validateAcademicLinks(schoolId:string,termId:string,classIds:string[]){const [term,count]=await Promise.all([this.database.term.findFirst({where:{id:termId,academicYear:{schoolId}}}),this.database.class.count({where:{id:{in:[...new Set(classIds)]},schoolId}})]);if(!term)throw new NotFoundException('Term not found');if(count!==new Set(classIds).size)throw new NotFoundException('One or more classes were not found')}
 private presentStructure(row:StructureRecord){return{id:row.id,name:row.name,termId:row.termId,term:row.term.name,year:Number(row.term.academicYear.name),status:this.title(row.status),updatedAt:row.updatedAt.toISOString(),items:row.items.map(item=>({id:item.id,label:item.name,amount:Number(item.amount)})),classIds:row.assignments.map(item=>item.classId),classes:row.assignments.map(item=>item.class.name),grade:row.assignments.map(item=>item.class.grade).filter((v,i,a)=>a.indexOf(v)===i).join(', ')||'Unassigned',batches:row._count.batches}}
 private presentInvoice(row:InvoiceRecord){const debit=row.items.reduce((s,i)=>s+Number(i.amount),0)+row.adjustments.filter(a=>a.type==='DEBIT').reduce((s,a)=>s+Number(a.amount),0);const credit=row.creditNotes.flatMap(n=>n.items).reduce((s,i)=>s+Number(i.amount),0)+row.adjustments.filter(a=>a.type==='CREDIT').reduce((s,a)=>s+Number(a.amount),0)+row.allocations.filter(a=>a.payment.status==='COMPLETED').reduce((s,a)=>s+Number(a.amount),0);return{id:row.id,invoiceNumber:row.invoiceNumber,studentId:row.studentId,student:`${row.student.firstName} ${row.student.lastName}`,term:`${row.term.name}, ${row.term.academicYear.name}`,status:this.title(row.status),issuedAt:row.issuedAt.toISOString(),dueAt:row.dueAt?.toISOString()??null,debit,credit,balance:debit-credit,items:row.items.map(item=>({id:item.id,label:item.description,amount:Number(item.amount)}))}}
 private presentBatch(row:any){const invoices=row.invoices as Array<any>;const total=invoices.flatMap(i=>i.items).reduce((s:number,i:any)=>s+Number(i.amount),0);const paid=invoices.reduce((sum:number,invoice:any)=>sum+(invoice.allocations??[]).filter((a:any)=>a.payment.status==='COMPLETED').reduce((s:number,a:any)=>s+Number(a.amount),0),0);return{id:row.id,structureId:row.feeStructureId,structureName:row.feeStructure.name,grade:row.feeStructure.assignments.map((a:any)=>a.class.name).join(', '),term:`${row.feeStructure.term.name}, ${row.feeStructure.term.academicYear.name}`,count:invoices.length,total,date:row.createdAt.toISOString(),status:paid>=total?'Paid':paid>0?'Partially paid':'Generated'}}
 private title(value:string){return value.charAt(0)+value.slice(1).toLowerCase()}
}
