import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'
import { translate, type TranslationKey } from '../i18n/translations'
import type { AcademicClass, AcademicYear, AuditEvent, Budget, CreateStudentInput, Expense, FeeStructure, InvoiceBatch, Language, SchoolSettings, StaffMember, StaffRole, Student, StudentPagination, StudentTransaction, UpdateStudentInput } from '../types'
import { expenses as seedExpenses, initialAuditEvents, initialBudgets, initialFeeStructures, initialInvoiceBatches, initialRoles, initialSchoolSettings, initialStaff, initialTransactions } from '../data/mockData'
import { apiRequest } from '../services/api'
import { useAuth } from './AuthContext'

interface AppContextValue { language: Language; setLanguage: (value: Language) => void; t: (key: TranslationKey) => string; sidebarOpen: boolean; setSidebarOpen: (value: boolean) => void; students: Student[]; studentsLoading:boolean; studentPagination:StudentPagination; academicClasses:AcademicClass[]; academicYears:AcademicYear[]; loadStudents:(options?:{page?:number;pageSize?:number;search?:string;classId?:string})=>Promise<void>; transactions: StudentTransaction[]; feeStructures:FeeStructure[]; invoiceBatches:InvoiceBatch[]; feesLoading:boolean; loadFees:()=>Promise<void>; expenses:Expense[]; budgets:Budget[]; auditEvents:AuditEvent[]; staff:StaffMember[]; roles:StaffRole[]; schoolSettings:SchoolSettings; addStudent:(student:CreateStudentInput)=>Promise<Student>; updateStudent:(studentId:string,changes:UpdateStudentInput)=>Promise<Student>; recordPayment:(studentId:string,amount:number,method:string,reference:string)=>Promise<StudentTransaction>; voidPayment:(transactionId:string,reason:string)=>Promise<void>; saveFeeStructure:(structure:FeeStructure)=>Promise<FeeStructure>; generateInvoices:(structure:FeeStructure)=>Promise<InvoiceBatch>; addExpense:(expense:Expense)=>void; reviewExpense:(id:string,status:'Approved'|'Rejected',note:string)=>void; saveBudget:(budget:Budget)=>void; approveBudget:(id:string)=>void; saveStaff:(member:StaffMember)=>void; updateStaffStatus:(id:string,status:StaffMember['status'])=>void; saveRole:(role:StaffRole)=>void; saveSchoolSettings:(settings:SchoolSettings)=>void; resetDemo:()=>void }
const AppContext = createContext<AppContextValue | null>(null)

export function AppProvider({ children }: { children: ReactNode }) {
  const {user,hasPermission}=useAuth()
  const [language, setLanguage] = useState<Language>(()=>localStorage.getItem('shulefinance_language')==='sw'?'sw':'en')
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [students,setStudents]=useState<Student[]>([])
  const [studentsLoading,setStudentsLoading]=useState(false)
  const [studentPagination,setStudentPagination]=useState<StudentPagination>({page:1,pageSize:20,total:0,totalPages:0})
  const [academicClasses,setAcademicClasses]=useState<AcademicClass[]>([])
  const [academicYears,setAcademicYears]=useState<AcademicYear[]>([])
  const [transactions,setTransactions]=useState<StudentTransaction[]>([])
  const [feeStructures,setFeeStructures]=useState<FeeStructure[]>([])
  const [invoiceBatches,setInvoiceBatches]=useState<InvoiceBatch[]>([])
  const [feesLoading,setFeesLoading]=useState(false)
  const [expenses,setExpenses]=useState<Expense[]>(()=>{try{return JSON.parse(localStorage.getItem('shulefinance_expenses')||'null')||seedExpenses}catch{return seedExpenses}})
  const [budgets,setBudgets]=useState<Budget[]>(()=>{try{return JSON.parse(localStorage.getItem('shulefinance_budgets')||'null')||initialBudgets}catch{return initialBudgets}})
  const [auditEvents,setAuditEvents]=useState<AuditEvent[]>(()=>{try{return JSON.parse(localStorage.getItem('shulefinance_audit')||'null')||initialAuditEvents}catch{return initialAuditEvents}})
  const [staff,setStaff]=useState<StaffMember[]>(()=>{try{return JSON.parse(localStorage.getItem('shulefinance_staff')||'null')||initialStaff}catch{return initialStaff}})
  const [roles,setRoles]=useState<StaffRole[]>(()=>{try{return JSON.parse(localStorage.getItem('shulefinance_roles')||'null')||initialRoles}catch{return initialRoles}})
  const [schoolSettings,setSchoolSettings]=useState<SchoolSettings>(()=>{try{return JSON.parse(localStorage.getItem('shulefinance_settings')||'null')||initialSchoolSettings}catch{return initialSchoolSettings}})
  const audit=(event:Omit<AuditEvent,'id'|'timestamp'|'user'|'role'|'ipAddress'>)=>{const entry:AuditEvent={...event,id:`AUD-${String(Date.now()).slice(-9)}`,timestamp:new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date()),user:'Catherine Njeri',role:'School Accountant',ipAddress:'192.168.1.24'};setAuditEvents(current=>{const next=[entry,...current];localStorage.setItem('shulefinance_audit',JSON.stringify(next));return next})}
  const loadStudents=useCallback(async(options:{page?:number;pageSize?:number;search?:string;classId?:string}={})=>{if(!user||!hasPermission('students.view'))return;setStudentsLoading(true);try{const params=new URLSearchParams({page:String(options.page||1),pageSize:String(options.pageSize||20)});if(options.search)params.set('search',options.search);if(options.classId)params.set('classId',options.classId);const [studentResult,classResult,yearResult]=await Promise.all([apiRequest<{students:Student[];pagination:StudentPagination}>(`/students?${params}`),apiRequest<{classes:AcademicClass[]}>('/classes'),apiRequest<{academicYears:AcademicYear[]}>('/academic-years')]);setStudents(studentResult.students);setStudentPagination(studentResult.pagination);setAcademicClasses(classResult.classes);setAcademicYears(yearResult.academicYears)}finally{setStudentsLoading(false)}},[user,hasPermission])
  useEffect(()=>{if(user&&hasPermission('students.view'))void loadStudents({pageSize:20});else{setStudents([]);setAcademicClasses([]);setAcademicYears([])}},[user,hasPermission,loadStudents])
  const loadFees=useCallback(async()=>{if(!user||!hasPermission('fees.view'))return;setFeesLoading(true);try{const [structures,batches]=await Promise.all([apiRequest<{feeStructures:FeeStructure[]}>('/fee-structures'),apiRequest<{invoiceBatches:InvoiceBatch[]}>('/invoice-batches')]);setFeeStructures(structures.feeStructures);setInvoiceBatches(batches.invoiceBatches)}finally{setFeesLoading(false)}},[user,hasPermission])
  useEffect(()=>{if(user&&hasPermission('fees.view'))void loadFees();else{setFeeStructures([]);setInvoiceBatches([])}},[user,hasPermission,loadFees])
  const toTransaction=(payment:{id:string;receiptNumber:string;studentId:string|null;method:string;reference:string;amount:number;status:string;receivedAt:string}):StudentTransaction=>({id:payment.receiptNumber,backendId:payment.id,studentId:payment.studentId||'',type:'Payment',description:'Fee payment',date:new Date(payment.receivedAt).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}),amount:payment.amount,method:payment.method==='MPESA'?'M-Pesa':payment.method.charAt(0)+payment.method.slice(1).toLowerCase(),reference:payment.reference,status:(payment.status.charAt(0)+payment.status.slice(1).toLowerCase()) as StudentTransaction['status']})
  const loadPayments=useCallback(async()=>{if(!user||!hasPermission('payments.view'))return;const result=await apiRequest<{payments:Array<{id:string;receiptNumber:string;studentId:string|null;method:string;reference:string;amount:number;status:string;receivedAt:string}>}>('/payments?pageSize=100');setTransactions(result.payments.map(toTransaction))},[user,hasPermission])
  useEffect(()=>{if(user&&hasPermission('payments.view'))void loadPayments();else setTransactions([])},[user,hasPermission,loadPayments])
  const saveStudents=(next:Student[])=>{setStudents(next)}
  const saveTransactions=(next:StudentTransaction[])=>{setTransactions(next)}
  const addStudent=async(input:CreateStudentInput)=>{const result=await apiRequest<{student:Student}>('/students',{method:'POST',body:JSON.stringify(input)});setStudents(current=>[result.student,...current]);setStudentPagination(current=>({...current,total:current.total+1}));return result.student}
  const updateStudent=async(studentId:string,changes:UpdateStudentInput)=>{const result=await apiRequest<{student:Student}>(`/students/${studentId}`,{method:'PATCH',body:JSON.stringify(changes)});setStudents(current=>current.map(student=>student.id===studentId?result.student:student));return result.student}
  const recordPayment=async(studentId:string,amount:number,method:string,reference:string)=>{const result=await apiRequest<{payment:{id:string;receiptNumber:string;studentId:string|null;method:string;reference:string;amount:number;status:string;receivedAt:string}}>('/payments',{method:'POST',body:JSON.stringify({studentId,amount,method:method==='M-Pesa'?'MPESA':method.toUpperCase(),reference,idempotencyKey:crypto.randomUUID()})});const transaction=toTransaction(result.payment);setTransactions(current=>[transaction,...current.filter(item=>item.backendId!==transaction.backendId)]);await loadStudents({pageSize:20});return transaction}
  const voidPayment=async(transactionId:string,reason:string)=>{const payment=transactions.find(item=>(item.backendId===transactionId||item.id===transactionId)&&item.type==='Payment');if(!payment?.backendId||payment.status==='Voided')return;await apiRequest(`/payments/${payment.backendId}/reverse`,{method:'POST',body:JSON.stringify({reason,idempotencyKey:crypto.randomUUID()})});setTransactions(current=>current.map(item=>item.backendId===payment.backendId?{...item,status:'Voided'}:item));await loadStudents({pageSize:20})}
  const saveFeeStructure=async(structure:FeeStructure)=>{const exists=feeStructures.some(item=>item.id===structure.id);const term=academicYears.flatMap(year=>year.terms.map(item=>({...item,year}))).find(item=>item.id===structure.termId);if(!term)throw new Error('Select a valid academic term');const payload={name:structure.name,termId:structure.termId,status:structure.status.toUpperCase(),items:structure.items.map(item=>({label:item.label,amount:item.amount})),classIds:structure.classIds||[]};const result=await apiRequest<{feeStructure:FeeStructure}>(exists?`/fee-structures/${structure.id}`:'/fee-structures',{method:exists?'PATCH':'POST',body:JSON.stringify(payload)});setFeeStructures(current=>exists?current.map(item=>item.id===result.feeStructure.id?result.feeStructure:item):[result.feeStructure,...current]);return result.feeStructure}
  const generateInvoices=async(structure:FeeStructure)=>{const key=`web-${structure.id}-${new Date(structure.updatedAt).getTime()}`;const result=await apiRequest<{batch:InvoiceBatch}>(`/fee-structures/${structure.id}/generate-invoices`,{method:'POST',body:JSON.stringify({idempotencyKey:key})});setInvoiceBatches(current=>current.some(item=>item.id===result.batch.id)?current:[result.batch,...current]);await loadStudents({pageSize:20});return result.batch}
  const saveExpenses=(next:Expense[])=>{setExpenses(next);localStorage.setItem('shulefinance_expenses',JSON.stringify(next))}
  const addExpense=(expense:Expense)=>{saveExpenses([expense,...expenses]);audit({action:'Expense submitted',module:'Expenses',recordId:expense.id,description:`Submitted ${expense.description} for KSh ${expense.amount.toLocaleString()} for approval.`,severity:'Warning'})}
  const reviewExpense=(id:string,status:'Approved'|'Rejected',note:string)=>{const expense=expenses.find(item=>item.id===id);saveExpenses(expenses.map(expense=>expense.id===id?{...expense,status,reviewNote:note,approvedBy:status==='Approved'?'Dr. James Mwangi':undefined}:expense));audit({action:`Expense ${status.toLowerCase()}`,module:'Expenses',recordId:id,description:`${status} ${expense?.description||'expense request'} for KSh ${(expense?.amount||0).toLocaleString()}.`,severity:status==='Approved'?'Success':'Critical',changes:[{field:'Status',before:'Pending',after:status}]})}
  const saveBudgets=(next:Budget[])=>{setBudgets(next);localStorage.setItem('shulefinance_budgets',JSON.stringify(next))}
  const saveBudget=(budget:Budget)=>{const exists=budgets.some(item=>item.id===budget.id);saveBudgets(exists?budgets.map(item=>item.id===budget.id?budget:item):[budget,...budgets]);audit({action:exists?'Budget updated':'Budget created',module:'Budgets',recordId:budget.id,description:`${exists?'Updated':'Created'} ${budget.name} with KSh ${budget.items.reduce((sum,item)=>sum+item.allocated,0).toLocaleString()} allocated.`,severity:budget.status==='Pending'?'Warning':'Info'})}
  const approveBudget=(id:string)=>{const budget=budgets.find(item=>item.id===id);saveBudgets(budgets.map(budget=>budget.id===id?{...budget,status:'Approved',approvedBy:'Dr. James Mwangi',updatedAt:new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(new Date())}:budget));audit({action:'Budget approved',module:'Budgets',recordId:id,description:`Approved ${budget?.name||'budget'} as the active spending plan.`,severity:'Success',changes:[{field:'Status',before:budget?.status||'Pending',after:'Approved'}]})}
  const saveStaffList=(next:StaffMember[])=>{setStaff(next);localStorage.setItem('shulefinance_staff',JSON.stringify(next))}
  const saveStaff=(member:StaffMember)=>{const exists=staff.some(item=>item.id===member.id);saveStaffList(exists?staff.map(item=>item.id===member.id?member:item):[member,...staff]);audit({action:exists?'Staff access updated':'Staff member invited',module:'Team',recordId:member.id,description:`${exists?'Updated access for':'Sent an invitation to'} ${member.name} as ${roles.find(role=>role.id===member.roleId)?.name||'staff'}.`,severity:'Info'})}
  const updateStaffStatus=(id:string,status:StaffMember['status'])=>{const member=staff.find(item=>item.id===id);saveStaffList(staff.map(item=>item.id===id?{...item,status}:item));audit({action:status==='Suspended'?'Staff access suspended':'Staff access restored',module:'Team',recordId:id,description:`Changed ${member?.name||'staff member'} access status to ${status}.`,severity:status==='Suspended'?'Critical':'Success',changes:[{field:'Access status',before:member?.status||'Unknown',after:status}]})}
  const saveRole=(role:StaffRole)=>{const exists=roles.some(item=>item.id===role.id);const next=exists?roles.map(item=>item.id===role.id?role:item):[role,...roles];setRoles(next);localStorage.setItem('shulefinance_roles',JSON.stringify(next));audit({action:exists?'Role permissions updated':'Custom role created',module:'Team',recordId:role.id,description:`${exists?'Updated permissions for':'Created'} the ${role.name} role.`,severity:'Warning'})}
  const saveSchoolSettings=(settings:SchoolSettings)=>{setSchoolSettings(settings);localStorage.setItem('shulefinance_settings',JSON.stringify(settings));audit({action:'School settings updated',module:'System',recordId:'SETTINGS',description:'Updated school configuration and finance preferences.',severity:'Warning'})}
  const resetDemo=()=>{saveTransactions(initialTransactions);setFeeStructures(initialFeeStructures);setInvoiceBatches(initialInvoiceBatches);saveExpenses(seedExpenses);saveBudgets(initialBudgets);setAuditEvents(initialAuditEvents);setStaff(initialStaff);setRoles(initialRoles);setSchoolSettings(initialSchoolSettings);localStorage.setItem('shulefinance_audit',JSON.stringify(initialAuditEvents));['shulefinance_students','shulefinance_fee_structures','shulefinance_invoice_batches','shulefinance_staff','shulefinance_roles','shulefinance_settings'].forEach(key=>localStorage.removeItem(key));void loadStudents()}
  const value = useMemo(() => ({ language, setLanguage, t: (key: TranslationKey) => translate(language, key), sidebarOpen, setSidebarOpen,students,studentsLoading,studentPagination,academicClasses,academicYears,loadStudents,transactions,feeStructures,invoiceBatches,feesLoading,loadFees,expenses,budgets,auditEvents,staff,roles,schoolSettings,addStudent,updateStudent,recordPayment,voidPayment,saveFeeStructure,generateInvoices,addExpense,reviewExpense,saveBudget,approveBudget,saveStaff,updateStaffStatus,saveRole,saveSchoolSettings,resetDemo }), [language, sidebarOpen,students,studentsLoading,studentPagination,academicClasses,academicYears,loadStudents,transactions,feeStructures,invoiceBatches,feesLoading,loadFees,expenses,budgets,auditEvents,staff,roles,schoolSettings])
  return <AppContext.Provider value={value}>{children}</AppContext.Provider>
}

export function useApp() {
  const context = useContext(AppContext)
  if (!context) throw new Error('useApp must be used within AppProvider')
  return context
}
