import { createContext, useContext, useMemo, useState, type ReactNode } from 'react'
import { translate, type TranslationKey } from '../i18n/translations'
import type { AuditEvent, Budget, Expense, FeeStructure, InvoiceBatch, Language, SchoolSettings, StaffMember, StaffRole, Student, StudentTransaction } from '../types'
import { expenses as seedExpenses, initialAuditEvents, initialBudgets, initialFeeStructures, initialInvoiceBatches, initialRoles, initialSchoolSettings, initialStaff, initialTransactions, students as seedStudents } from '../data/mockData'

interface AppContextValue { language: Language; setLanguage: (value: Language) => void; t: (key: TranslationKey) => string; sidebarOpen: boolean; setSidebarOpen: (value: boolean) => void; students: Student[]; transactions: StudentTransaction[]; feeStructures:FeeStructure[]; invoiceBatches:InvoiceBatch[]; expenses:Expense[]; budgets:Budget[]; auditEvents:AuditEvent[]; staff:StaffMember[]; roles:StaffRole[]; schoolSettings:SchoolSettings; addStudent:(student:Student)=>void; updateStudent:(student:Student)=>void; recordPayment:(studentId:string,amount:number,method:string,reference:string)=>StudentTransaction; voidPayment:(transactionId:string)=>void; saveFeeStructure:(structure:FeeStructure)=>void; generateInvoices:(structure:FeeStructure)=>InvoiceBatch; addExpense:(expense:Expense)=>void; reviewExpense:(id:string,status:'Approved'|'Rejected',note:string)=>void; saveBudget:(budget:Budget)=>void; approveBudget:(id:string)=>void; saveStaff:(member:StaffMember)=>void; updateStaffStatus:(id:string,status:StaffMember['status'])=>void; saveRole:(role:StaffRole)=>void; saveSchoolSettings:(settings:SchoolSettings)=>void; resetDemo:()=>void }
const AppContext = createContext<AppContextValue | null>(null)

export function AppProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(()=>localStorage.getItem('shulefinance_language')==='sw'?'sw':'en')
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [students,setStudents]=useState<Student[]>(()=>{try{return JSON.parse(localStorage.getItem('shulefinance_students')||'null')||seedStudents}catch{return seedStudents}})
  const [transactions,setTransactions]=useState<StudentTransaction[]>(()=>{try{return JSON.parse(localStorage.getItem('shulefinance_transactions')||'null')||initialTransactions}catch{return initialTransactions}})
  const [feeStructures,setFeeStructures]=useState<FeeStructure[]>(()=>{try{return JSON.parse(localStorage.getItem('shulefinance_fee_structures')||'null')||initialFeeStructures}catch{return initialFeeStructures}})
  const [invoiceBatches,setInvoiceBatches]=useState<InvoiceBatch[]>(()=>{try{return JSON.parse(localStorage.getItem('shulefinance_invoice_batches')||'null')||initialInvoiceBatches}catch{return initialInvoiceBatches}})
  const [expenses,setExpenses]=useState<Expense[]>(()=>{try{return JSON.parse(localStorage.getItem('shulefinance_expenses')||'null')||seedExpenses}catch{return seedExpenses}})
  const [budgets,setBudgets]=useState<Budget[]>(()=>{try{return JSON.parse(localStorage.getItem('shulefinance_budgets')||'null')||initialBudgets}catch{return initialBudgets}})
  const [auditEvents,setAuditEvents]=useState<AuditEvent[]>(()=>{try{return JSON.parse(localStorage.getItem('shulefinance_audit')||'null')||initialAuditEvents}catch{return initialAuditEvents}})
  const [staff,setStaff]=useState<StaffMember[]>(()=>{try{return JSON.parse(localStorage.getItem('shulefinance_staff')||'null')||initialStaff}catch{return initialStaff}})
  const [roles,setRoles]=useState<StaffRole[]>(()=>{try{return JSON.parse(localStorage.getItem('shulefinance_roles')||'null')||initialRoles}catch{return initialRoles}})
  const [schoolSettings,setSchoolSettings]=useState<SchoolSettings>(()=>{try{return JSON.parse(localStorage.getItem('shulefinance_settings')||'null')||initialSchoolSettings}catch{return initialSchoolSettings}})
  const audit=(event:Omit<AuditEvent,'id'|'timestamp'|'user'|'role'|'ipAddress'>)=>{const entry:AuditEvent={...event,id:`AUD-${String(Date.now()).slice(-9)}`,timestamp:new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date()),user:'Catherine Njeri',role:'School Accountant',ipAddress:'192.168.1.24'};setAuditEvents(current=>{const next=[entry,...current];localStorage.setItem('shulefinance_audit',JSON.stringify(next));return next})}
  const saveStudents=(next:Student[])=>{setStudents(next);localStorage.setItem('shulefinance_students',JSON.stringify(next))}
  const saveTransactions=(next:StudentTransaction[])=>{setTransactions(next);localStorage.setItem('shulefinance_transactions',JSON.stringify(next))}
  const addStudent=(student:Student)=>{saveStudents([student,...students]);audit({action:'Student account created',module:'Students',recordId:student.admission,description:`Created a financial account for ${student.name} in ${student.grade}.`,severity:'Success'})}
  const updateStudent=(student:Student)=>{const previous=students.find(item=>item.id===student.id);saveStudents(students.map(item=>item.id===student.id?student:item));audit({action:'Student details updated',module:'Students',recordId:student.admission,description:`Updated profile and guardian details for ${student.name}.`,severity:'Info',changes:previous?[{field:'Guardian',before:previous.guardian,after:student.guardian},{field:'Phone',before:previous.phone,after:student.phone}]:undefined})}
  const recordPayment=(studentId:string,amount:number,method:string,reference:string)=>{const student=students.find(item=>item.id===studentId);const transaction:StudentTransaction={id:`RCT-${String(Date.now()).slice(-5)}`,studentId,type:'Payment',description:'Fee payment',date:new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(new Date()),amount,method,reference,status:'Completed'};saveTransactions([transaction,...transactions]);saveStudents(students.map(student=>student.id===studentId?{...student,paid:Math.min(student.billed,student.paid+amount),status:student.paid+amount>=student.billed?'Paid':'Partial'}:student));audit({action:'Payment recorded',module:'Payments',recordId:transaction.id,description:`Recorded a ${method} payment of KSh ${amount.toLocaleString()} for ${student?.name||studentId}.`,severity:'Success',changes:student?[{field:'Student balance',before:`KSh ${(student.billed-student.paid).toLocaleString()}`,after:`KSh ${Math.max(0,student.billed-student.paid-amount).toLocaleString()}`}]:undefined});return transaction}
  const voidPayment=(transactionId:string)=>{const payment=transactions.find(item=>item.id===transactionId&&item.type==='Payment');if(!payment||payment.status==='Voided')return;saveTransactions(transactions.map(item=>item.id===transactionId?{...item,status:'Voided'}:item));saveStudents(students.map(student=>{if(student.id!==payment.studentId)return student;const paid=Math.max(0,student.paid-payment.amount);return{...student,paid,status:paid===0?'Overdue':paid>=student.billed?'Paid':'Partial'}}));audit({action:'Payment reversed',module:'Payments',recordId:transactionId,description:`Voided a payment of KSh ${payment.amount.toLocaleString()} and restored the student balance.`,severity:'Critical',changes:[{field:'Payment status',before:'Completed',after:'Voided'}]})}
  const saveFeeStructure=(structure:FeeStructure)=>{const exists=feeStructures.some(item=>item.id===structure.id);const next=exists?feeStructures.map(item=>item.id===structure.id?structure:item):[structure,...feeStructures];setFeeStructures(next);localStorage.setItem('shulefinance_fee_structures',JSON.stringify(next));audit({action:exists?'Fee structure updated':'Fee structure created',module:'Fees',recordId:structure.id,description:`${exists?'Updated':'Created'} ${structure.name} for ${structure.term}, ${structure.year}.`,severity:'Info'})}
  const generateInvoices=(structure:FeeStructure)=>{const recipients=students.filter(student=>student.grade.startsWith(structure.grade));const amount=structure.items.reduce((sum,item)=>sum+item.amount,0);const now=new Date();const date=new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(now);const batch:InvoiceBatch={id:`BAT-${String(Date.now()).slice(-6)}`,structureId:structure.id,structureName:structure.name,grade:structure.grade,term:`${structure.term}, ${structure.year}`,count:recipients.length,total:amount*recipients.length,date,status:'Generated'};const nextBatches=[batch,...invoiceBatches];setInvoiceBatches(nextBatches);localStorage.setItem('shulefinance_invoice_batches',JSON.stringify(nextBatches));const ids=new Set(recipients.map(student=>student.id));saveStudents(students.map(student=>ids.has(student.id)?{...student,billed:student.billed+amount,status:'Overdue'}:student));saveTransactions([...recipients.map((student,index):StudentTransaction=>({id:`INV-${structure.year}-${String(Date.now()).slice(-4)}${index}`,studentId:student.id,type:'Invoice',description:`${structure.term} fee invoice`,date,amount,status:'Completed'})),...transactions]);saveFeeStructure({...structure,status:'Active',updatedAt:date});return batch}
  const saveExpenses=(next:Expense[])=>{setExpenses(next);localStorage.setItem('shulefinance_expenses',JSON.stringify(next))}
  const addExpense=(expense:Expense)=>{saveExpenses([expense,...expenses]);audit({action:'Expense submitted',module:'Expenses',recordId:expense.id,description:`Submitted ${expense.description} for KSh ${expense.amount.toLocaleString()} for approval.`,severity:'Warning'})}
  const reviewExpense=(id:string,status:'Approved'|'Rejected',note:string)=>{const expense=expenses.find(item=>item.id===id);saveExpenses(expenses.map(expense=>expense.id===id?{...expense,status,reviewNote:note,approvedBy:status==='Approved'?'Dr. James Mwangi':undefined}:expense));audit({action:`Expense ${status.toLowerCase()}`,module:'Expenses',recordId:id,description:`${status} ${expense?.description||'expense request'} for KSh ${(expense?.amount||0).toLocaleString()}.`,severity:status==='Approved'?'Success':'Critical',changes:[{field:'Status',before:'Pending',after:status}]})}
  const saveBudgets=(next:Budget[])=>{setBudgets(next);localStorage.setItem('shulefinance_budgets',JSON.stringify(next))}
  const saveBudget=(budget:Budget)=>{const exists=budgets.some(item=>item.id===budget.id);saveBudgets(exists?budgets.map(item=>item.id===budget.id?budget:item):[budget,...budgets]);audit({action:exists?'Budget updated':'Budget created',module:'Budgets',recordId:budget.id,description:`${exists?'Updated':'Created'} ${budget.name} with KSh ${budget.items.reduce((sum,item)=>sum+item.allocated,0).toLocaleString()} allocated.`,severity:budget.status==='Pending'?'Warning':'Info'})}
  const approveBudget=(id:string)=>{const budget=budgets.find(item=>item.id===id);saveBudgets(budgets.map(budget=>budget.id===id?{...budget,status:'Approved',approvedBy:'Dr. James Mwangi',updatedAt:new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(new Date())}:budget));audit({action:'Budget approved',module:'Budgets',recordId:id,description:`Approved ${budget?.name||'budget'} as the active spending plan.`,severity:'Success',changes:[{field:'Status',before:budget?.status||'Pending',after:'Approved'}]})}
  const saveStaffList=(next:StaffMember[])=>{setStaff(next);localStorage.setItem('shulefinance_staff',JSON.stringify(next))}
  const saveStaff=(member:StaffMember)=>{const exists=staff.some(item=>item.id===member.id);saveStaffList(exists?staff.map(item=>item.id===member.id?member:item):[member,...staff]);audit({action:exists?'Staff access updated':'Staff member invited',module:'Team',recordId:member.id,description:`${exists?'Updated access for':'Sent an invitation to'} ${member.name} as ${roles.find(role=>role.id===member.roleId)?.name||'staff'}.`,severity:'Info'})}
  const updateStaffStatus=(id:string,status:StaffMember['status'])=>{const member=staff.find(item=>item.id===id);saveStaffList(staff.map(item=>item.id===id?{...item,status}:item));audit({action:status==='Suspended'?'Staff access suspended':'Staff access restored',module:'Team',recordId:id,description:`Changed ${member?.name||'staff member'} access status to ${status}.`,severity:status==='Suspended'?'Critical':'Success',changes:[{field:'Access status',before:member?.status||'Unknown',after:status}]})}
  const saveRole=(role:StaffRole)=>{const exists=roles.some(item=>item.id===role.id);const next=exists?roles.map(item=>item.id===role.id?role:item):[role,...roles];setRoles(next);localStorage.setItem('shulefinance_roles',JSON.stringify(next));audit({action:exists?'Role permissions updated':'Custom role created',module:'Team',recordId:role.id,description:`${exists?'Updated permissions for':'Created'} the ${role.name} role.`,severity:'Warning'})}
  const saveSchoolSettings=(settings:SchoolSettings)=>{setSchoolSettings(settings);localStorage.setItem('shulefinance_settings',JSON.stringify(settings));audit({action:'School settings updated',module:'System',recordId:'SETTINGS',description:'Updated school configuration and finance preferences.',severity:'Warning'})}
  const resetDemo=()=>{saveStudents(seedStudents);saveTransactions(initialTransactions);setFeeStructures(initialFeeStructures);setInvoiceBatches(initialInvoiceBatches);saveExpenses(seedExpenses);saveBudgets(initialBudgets);setAuditEvents(initialAuditEvents);setStaff(initialStaff);setRoles(initialRoles);setSchoolSettings(initialSchoolSettings);localStorage.setItem('shulefinance_audit',JSON.stringify(initialAuditEvents));['shulefinance_fee_structures','shulefinance_invoice_batches','shulefinance_staff','shulefinance_roles','shulefinance_settings'].forEach(key=>localStorage.removeItem(key))}
  const value = useMemo(() => ({ language, setLanguage, t: (key: TranslationKey) => translate(language, key), sidebarOpen, setSidebarOpen,students,transactions,feeStructures,invoiceBatches,expenses,budgets,auditEvents,staff,roles,schoolSettings,addStudent,updateStudent,recordPayment,voidPayment,saveFeeStructure,generateInvoices,addExpense,reviewExpense,saveBudget,approveBudget,saveStaff,updateStaffStatus,saveRole,saveSchoolSettings,resetDemo }), [language, sidebarOpen,students,transactions,feeStructures,invoiceBatches,expenses,budgets,auditEvents,staff,roles,schoolSettings])
  return <AppContext.Provider value={value}>{children}</AppContext.Provider>
}

export function useApp() {
  const context = useContext(AppContext)
  if (!context) throw new Error('useApp must be used within AppProvider')
  return context
}
