import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import Swal from 'sweetalert2'
import PageHeader from '../../components/PageHeader/PageHeader'
import StatusBadge from '../../components/StatusBadge/StatusBadge'
import { useApp } from '../../context/AppContext'
import { formatKES } from '../../utils/formatters'
import './Students.css'

export default function Students(){
 const {t,students,studentsLoading,studentPagination,academicClasses,academicYears,loadStudents,addStudent}=useApp();const navigate=useNavigate();const [query,setQuery]=useState('');const [classId,setClassId]=useState('');const [page,setPage]=useState(1)
 useEffect(()=>{const timer=window.setTimeout(()=>void loadStudents({page,pageSize:20,search:query||undefined,classId:classId||undefined}),300);return()=>window.clearTimeout(timer)},[query,classId,page,loadStudents])
 const activeTerm=academicYears.flatMap(year=>year.terms).find(term=>term.status==='ACTIVE')
 const openAddStudent=()=>{if(!activeTerm||!academicClasses.length){Swal.fire({title:'Academic setup required',text:'Create an active term and at least one class before adding students.',icon:'warning',confirmButtonColor:'#1f6b50'});return}Swal.fire({title:t('addStudent'),html:`<input id="student-name" class="swal2-input" placeholder="Full name"><input id="admission" class="swal2-input" placeholder="Admission number"><input id="guardian" class="swal2-input" placeholder="Guardian name"><input id="phone" class="swal2-input" placeholder="Guardian phone"><input id="guardian-email" type="email" class="swal2-input" placeholder="Guardian email (optional)"><select id="class" class="swal2-select">${academicClasses.map(item=>`<option value="${item.id}">${item.name}</option>`).join('')}</select>`,showCancelButton:true,confirmButtonText:'Save student',confirmButtonColor:'#1f6b50',showLoaderOnConfirm:true,preConfirm:async()=>{const field=(id:string)=>(document.getElementById(id) as HTMLInputElement).value;const fullName=field('student-name'),admissionNumber=field('admission'),guardianName=field('guardian'),guardianPhone=field('phone');if(!fullName||!admissionNumber||!guardianName||!guardianPhone){Swal.showValidationMessage('Student, admission, guardian, and phone are required');return false}try{return await addStudent({fullName,admissionNumber,guardianName,guardianPhone,guardianEmail:field('guardian-email')||undefined,classId:field('class'),termId:activeTerm.id})}catch(error){Swal.showValidationMessage(error instanceof Error?error.message:'Student could not be saved');return false}}}).then(result=>{if(result.isConfirmed&&result.value)Swal.fire({title:'Student added',text:`${result.value.name} is enrolled and stored in the database.`,icon:'success',confirmButtonColor:'#1f6b50'})})}
 const fullyPaid=students.filter(s=>s.status==='Paid').length;const partial=students.filter(s=>s.status==='Partial').length;const overdue=students.filter(s=>s.status==='Overdue').length
 return <div><PageHeader eyebrow="STUDENT FINANCE" title={t('studentsTitle')} subtitle={t('studentsSub')} actions={<><button className="button button--light" onClick={()=>Swal.fire({title:'Export ready',text:'The student accounts report has been prepared for download.',icon:'success',confirmButtonColor:'#1f6b50'})}><span className="material-symbols-rounded">download</span>{t('export')}</button><button className="button button--primary" onClick={openAddStudent}><span className="material-symbols-rounded">person_add</span>{t('addStudent')}</button></>}/>
 <section className="student-summary"><div><span className="material-symbols-rounded">groups</span><p><strong>{studentPagination.total}</strong><small>{t('allStudents')}</small></p></div><div><span className="material-symbols-rounded">check_circle</span><p><strong>{fullyPaid}</strong><small>Fully paid on this page</small></p></div><div><span className="material-symbols-rounded">pending_actions</span><p><strong>{partial}</strong><small>Partial on this page</small></p></div><div><span className="material-symbols-rounded">error</span><p><strong>{overdue}</strong><small>Overdue on this page</small></p></div></section>
 <section className="students-panel"><div className="students-toolbar"><div className="students-search"><span className="material-symbols-rounded">search</span><input value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}} placeholder="Search by name, admission or guardian"/></div><select value={classId} onChange={event=>{setClassId(event.target.value);setPage(1)}}><option value="">All classes</option>{academicClasses.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select><button className="button button--light"><span className="material-symbols-rounded">tune</span>{t('filter')}</button></div>
 <div className="table-wrap"><table className="students-table"><thead><tr><th>{t('student')}</th><th>{t('grade')}</th><th>{t('guardian')}</th><th>{t('billed')}</th><th>{t('paid')}</th><th>{t('balance')}</th><th>{t('status')}</th><th>{t('actions')}</th></tr></thead><tbody>{students.map(student=><tr className="clickable-row" key={student.id} onClick={()=>navigate(`/students/${student.id}`)}><td><div className="student-cell"><span style={{background:student.color}}>{student.initials}</span><div><strong>{student.name}</strong><small>{student.admission}</small></div></div></td><td><span className="class-tag">{student.grade}</span></td><td><strong>{student.guardian}</strong><small className="cell-small">{student.phone}</small></td><td>{formatKES(student.billed)}</td><td className="paid-amount">{formatKES(student.paid)}</td><td className={student.billed-student.paid>0?'balance-due':''}>{formatKES(student.billed-student.paid)}</td><td><StatusBadge status={student.status}/></td><td><button className="row-action" onClick={event=>{event.stopPropagation();navigate(`/students/${student.id}`)}}><span className="material-symbols-rounded">arrow_forward</span></button></td></tr>)}</tbody></table>{studentsLoading&&<div className="empty-state"><span className="material-symbols-rounded">sync</span><p>Loading students…</p></div>}{!studentsLoading&&!students.length&&<div className="empty-state"><span className="material-symbols-rounded">person_search</span><p>No students match this search.</p></div>}</div><div className="table-footer"><span>Showing {students.length} of {studentPagination.total} students</span><div><button disabled={page<=1||studentsLoading} onClick={()=>setPage(value=>value-1)}><span className="material-symbols-rounded">chevron_left</span></button><button className="current">{page}</button><button disabled={page>=studentPagination.totalPages||studentsLoading} onClick={()=>setPage(value=>value+1)}><span className="material-symbols-rounded">chevron_right</span></button></div></div></section></div>
}
