import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import Swal from 'sweetalert2'
import PageHeader from '../../components/PageHeader/PageHeader'
import StatusBadge from '../../components/StatusBadge/StatusBadge'
import { useApp } from '../../context/AppContext'
import { formatKES } from '../../utils/formatters'
import './Students.css'

export default function Students(){
 const {t,students,addStudent}=useApp();const navigate=useNavigate();const [query,setQuery]=useState('');const [grade,setGrade]=useState('All classes')
 const filtered=useMemo(()=>students.filter(s=>(s.name+s.admission+s.guardian).toLowerCase().includes(query.toLowerCase())&&(grade==='All classes'||s.grade.startsWith(grade))),[query,grade,students])
 const openAddStudent=()=>Swal.fire({title:t('addStudent'),html:'<input id="student-name" class="swal2-input" placeholder="Full name"><input id="admission" class="swal2-input" placeholder="Admission number"><input id="guardian" class="swal2-input" placeholder="Guardian name"><input id="phone" class="swal2-input" placeholder="Guardian phone"><select id="class" class="swal2-select"><option>Grade 6 A</option><option>Grade 7 B</option><option>Grade 8 A</option></select>',showCancelButton:true,confirmButtonText:'Save student',confirmButtonColor:'#1f6b50',preConfirm:()=>{const field=(id:string)=>(document.getElementById(id) as HTMLInputElement).value;const name=field('student-name');const admission=field('admission');if(!name||!admission){Swal.showValidationMessage('Name and admission number are required');return false}return{name,admission,guardian:field('guardian')||'Not provided',phone:field('phone')||'Not provided',grade:field('class')}}}).then(r=>{if(r.isConfirmed&&r.value){const value=r.value;const words=value.name.trim().split(/\s+/);addStudent({id:`ST-${Date.now()}`,name:value.name,admission:value.admission,grade:value.grade,guardian:value.guardian,phone:value.phone,billed:35000,paid:0,status:'Overdue',initials:words.map((word:string)=>word[0]).join('').slice(0,2).toUpperCase(),color:'#d6eee3'});Swal.fire({title:'Student added',text:`${value.name} now has an active fee account.`,icon:'success',confirmButtonColor:'#1f6b50'})}})
 const fullyPaid=students.filter(s=>s.status==='Paid').length;const partial=students.filter(s=>s.status==='Partial').length;const overdue=students.filter(s=>s.status==='Overdue').length
 return <div><PageHeader eyebrow="STUDENT FINANCE" title={t('studentsTitle')} subtitle={t('studentsSub')} actions={<><button className="button button--light" onClick={()=>Swal.fire({title:'Export ready',text:'The student accounts report has been prepared for download.',icon:'success',confirmButtonColor:'#1f6b50'})}><span className="material-symbols-rounded">download</span>{t('export')}</button><button className="button button--primary" onClick={openAddStudent}><span className="material-symbols-rounded">person_add</span>{t('addStudent')}</button></>}/>
 <section className="student-summary"><div><span className="material-symbols-rounded">groups</span><p><strong>{students.length}</strong><small>{t('allStudents')}</small></p></div><div><span className="material-symbols-rounded">check_circle</span><p><strong>{fullyPaid}</strong><small>Fully paid</small></p></div><div><span className="material-symbols-rounded">pending_actions</span><p><strong>{partial}</strong><small>Partial payment</small></p></div><div><span className="material-symbols-rounded">error</span><p><strong>{overdue}</strong><small>Overdue</small></p></div></section>
 <section className="students-panel"><div className="students-toolbar"><div className="students-search"><span className="material-symbols-rounded">search</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name, admission or guardian"/></div><select value={grade} onChange={e=>setGrade(e.target.value)}><option>All classes</option><option>Grade 6</option><option>Grade 7</option><option>Grade 8</option></select><button className="button button--light"><span className="material-symbols-rounded">tune</span>{t('filter')}</button></div>
 <div className="table-wrap"><table className="students-table"><thead><tr><th>{t('student')}</th><th>{t('grade')}</th><th>{t('guardian')}</th><th>{t('billed')}</th><th>{t('paid')}</th><th>{t('balance')}</th><th>{t('status')}</th><th>{t('actions')}</th></tr></thead><tbody>{filtered.map(s=><tr className="clickable-row" key={s.id} onClick={()=>navigate(`/students/${s.id}`)}><td><div className="student-cell"><span style={{background:s.color}}>{s.initials}</span><div><strong>{s.name}</strong><small>{s.admission}</small></div></div></td><td><span className="class-tag">{s.grade}</span></td><td><strong>{s.guardian}</strong><small className="cell-small">{s.phone}</small></td><td>{formatKES(s.billed)}</td><td className="paid-amount">{formatKES(s.paid)}</td><td className={s.billed-s.paid>0?'balance-due':''}>{formatKES(s.billed-s.paid)}</td><td><StatusBadge status={s.status}/></td><td><button className="row-action" onClick={event=>{event.stopPropagation();navigate(`/students/${s.id}`)}}><span className="material-symbols-rounded">arrow_forward</span></button></td></tr>)}</tbody></table></div><div className="table-footer"><span>Showing {filtered.length} of {students.length} students</span><div><button disabled><span className="material-symbols-rounded">chevron_left</span></button><button className="current">1</button><button disabled><span className="material-symbols-rounded">chevron_right</span></button></div></div></section></div>
}
