import React, { useMemo, useState } from 'react'
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import Swal from 'sweetalert2'
import PageHeader from '../../components/PageHeader/PageHeader'
import StatusBadge from '../../components/StatusBadge/StatusBadge'
import { useApp } from '../../context/AppContext'
import type { Budget, BudgetItem } from '../../types'
import { formatKES } from '../../utils/formatters'
import './Budgets.css'

const availableCategories=['Salaries','Food','Utilities','Maintenance','Transport','Learning materials','Equipment','Security','Stationery','Other']
const blankBudget=():Budget=>({id:`BDG-${Date.now()}`,name:'',term:'Term 3',year:2026,status:'Draft',createdBy:'Catherine Njeri',updatedAt:'Just now',items:[{id:`BI-${Date.now()}`,category:'Salaries',allocated:0}]})

export default function Budgets(){
 const {budgets,expenses,saveBudget,approveBudget}=useApp();const [selectedId,setSelectedId]=useState(budgets.find(b=>b.status==='Approved')?.id||budgets[0]?.id);const [editor,setEditor]=useState<Budget|null>(null);const selected=budgets.find(b=>b.id===selectedId)||budgets[0]
 const actualByCategory=useMemo(()=>selected?.items.reduce<Record<string,number>>((totals,item)=>({...totals,[item.category]:item.actual||0}),{})||{},[selected]);if(!selected)return null
 const totalBudget=selected.items.reduce((sum,item)=>sum+item.allocated,0);const totalActual=selected.items.reduce((sum,item)=>sum+(actualByCategory[item.category]||0),0);const remaining=totalBudget-totalActual;const utilization=totalBudget?totalActual/totalBudget*100:0;const comparison=selected.items.map(item=>({category:item.category.length>12?`${item.category.slice(0,11)}…`:item.category,budget:item.allocated/1000,actual:(actualByCategory[item.category]||0)/1000}));const overBudget=selected.items.filter(item=>(actualByCategory[item.category]||0)>item.allocated)
 const updateItem=(id:string,patch:Partial<BudgetItem>)=>setEditor(current=>current?{...current,items:current.items.map(item=>item.id===id?{...item,...patch}:item)}:null)
 const persist=(submit=false)=>{if(!editor)return;if(!editor.name.trim()||editor.items.some(item=>item.allocated<=0)){Swal.fire({title:'Check budget details',text:'Enter a budget name and valid allocation for every category.',icon:'warning',confirmButtonColor:'#1f6b50'});return}const next={...editor,status:submit?'Pending' as const:editor.status,updatedAt:new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(new Date())};saveBudget(next);setSelectedId(next.id);setEditor(null);Swal.fire({title:submit?'Submitted for approval':'Budget saved',text:submit?'The principal can now review this budget.':'Your draft allocations have been saved.',icon:'success',confirmButtonColor:'#1f6b50'})}
 const approve=()=>Swal.fire({title:'Approve this budget?',html:`<div class="budget-approval"><span>Budget</span><b>${selected.name}</b><span>Period</span><b>${selected.term}, ${selected.year}</b><span>Total allocation</span><b>${formatKES(totalBudget)}</b></div><p class="approval-copy">Approval locks this version as the active spending plan.</p>`,icon:'question',showCancelButton:true,confirmButtonText:'Approve budget',confirmButtonColor:'#1f6b50'}).then(result=>{if(result.isConfirmed){approveBudget(selected.id);Swal.fire({title:'Budget approved',text:'The allocation is now active for expenditure control.',icon:'success',confirmButtonColor:'#1f6b50'})}})
 return <div className="budgets-page"><PageHeader eyebrow="PLANNING & CONTROL" title="Budget management" subtitle="Plan allocations and monitor spending against approved limits." actions={<><button className="button button--light" onClick={()=>setEditor({...selected,items:selected.items.map(i=>({...i}))})}><span className="material-symbols-rounded">edit</span>Edit allocations</button><button className="button button--primary" onClick={()=>setEditor(blankBudget())}><span className="material-symbols-rounded">add</span>Create budget</button></>}/>
 <section className="budget-selector"><div className="budget-selector__title"><div className="budget-icon"><span className="material-symbols-rounded">donut_large</span></div><div><span>VIEWING BUDGET</span><select value={selectedId} onChange={e=>setSelectedId(e.target.value)}>{budgets.map(b=><option value={b.id} key={b.id}>{b.name} · {b.term} {b.year}</option>)}</select></div></div><div className="budget-selector__meta"><div><span>Last updated</span><b>{selected.updatedAt}</b></div><div><span>Created by</span><b>{selected.createdBy}</b></div><StatusBadge status={selected.status}/>{selected.status==='Pending'&&<button className="button button--primary" onClick={approve}><span className="material-symbols-rounded">verified</span>Approve budget</button>}</div></section>
 <section className="budget-summary"><article><span>Total allocation</span><strong>{formatKES(totalBudget,true)}</strong><small>{selected.items.length} spending categories</small></article><article className="actual"><span>Actual spending</span><strong>{formatKES(totalActual,true)}</strong><small>{utilization.toFixed(1)}% utilized</small></article><article className={remaining<0?'negative-card':'remaining'}><span>Remaining balance</span><strong>{formatKES(remaining,true)}</strong><small>{remaining>=0?'Available to spend':'Budget exceeded'}</small></article><article><div className="util-head"><span>Budget utilization</span><b>{utilization.toFixed(1)}%</b></div><div className={`budget-progress ${utilization>100?'over':''}`}><i style={{width:`${Math.min(100,utilization)}%`}}/></div><small>{Math.max(0,100-utilization).toFixed(1)}% remaining</small></article></section>
 {overBudget.length>0&&<div className="budget-alert"><span className="material-symbols-rounded">warning</span><div><b>{overBudget.length} {overBudget.length===1?'category has':'categories have'} exceeded allocation</b><p>Review overspending in {overBudget.map(item=>item.category).join(', ')}.</p></div><button onClick={()=>document.getElementById('allocation-table')?.scrollIntoView({behavior:'smooth'})}>Review now</button></div>}
 <section className="budget-content"><article className="budget-chart panel"><div className="panel__head"><div><h2>Budget versus actual</h2><p>Category performance in KSh thousands</p></div><span className="chart-period">{selected.term}, {selected.year}</span></div><div className="budget-chart__canvas"><ResponsiveContainer width="100%" height="100%"><BarChart data={comparison} margin={{top:18,right:4,left:-20,bottom:0}}><CartesianGrid stroke="#edf1ef" vertical={false}/><XAxis dataKey="category" axisLine={false} tickLine={false} tick={{fontSize:8,fill:'#7d8b86'}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:8,fill:'#7d8b86'}}/><Tooltip formatter={(value)=>[`KSh ${Number(value).toLocaleString()}K`]}/><Legend wrapperStyle={{fontSize:'9px'}}/><Bar dataKey="budget" name="Budget" fill="#c9d9d2" radius={[4,4,0,0]}/><Bar dataKey="actual" name="Actual" fill="#23795b" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></article><aside className="budget-health-panel panel"><div className="panel__head"><div><h2>Budget health</h2><p>Allocation status overview</p></div></div><div className="health-ring" style={{'--percent':`${Math.min(100,utilization)*3.6}deg`} as React.CSSProperties}><div><strong>{utilization.toFixed(0)}%</strong><span>utilized</span></div></div><div className="health-legend"><div><i className="healthy"/><span>Within budget</span><b>{selected.items.length-overBudget.length}</b></div><div><i className="warning"/><span>Over budget</span><b>{overBudget.length}</b></div><div><i className="unused"/><span>No spending</span><b>{selected.items.filter(i=>!actualByCategory[i.category]).length}</b></div></div></aside></section>
 <section className="allocation-panel panel" id="allocation-table"><div className="allocation-head"><div><h2>Category allocations</h2><p>Detailed budget performance and available balances.</p></div><button className="button button--light" onClick={()=>setEditor({...selected,items:selected.items.map(i=>({...i}))})}><span className="material-symbols-rounded">tune</span>Adjust allocations</button></div><div className="table-wrap"><table><thead><tr><th>Category</th><th>Allocated budget</th><th>Actual spending</th><th>Remaining</th><th>Utilization</th><th>Status</th></tr></thead><tbody>{selected.items.map(item=>{const actual=actualByCategory[item.category]||0;const left=item.allocated-actual;const rate=item.allocated?actual/item.allocated*100:0;return <tr key={item.id}><td><div className="budget-category"><span className="material-symbols-rounded">{item.category==='Salaries'?'groups':item.category==='Food'?'restaurant':item.category==='Utilities'?'bolt':item.category==='Maintenance'?'handyman':'category'}</span><strong>{item.category}</strong></div></td><td><strong>{formatKES(item.allocated)}</strong></td><td>{formatKES(actual)}</td><td className={left<0?'over-amount':'left-amount'}>{formatKES(left)}</td><td><div className="table-progress"><i className={rate>100?'over':''} style={{width:`${Math.min(rate,100)}%`}}/></div><small>{rate.toFixed(0)}%</small></td><td><span className={`budget-state ${rate>100?'over':rate>80?'watch':actual===0?'unused':'good'}`}>{rate>100?'Over budget':rate>80?'Watch':actual===0?'Unused':'On track'}</span></td></tr>})}</tbody></table></div></section>
 {editor&&<div className="budget-modal"><div className="budget-backdrop" onClick={()=>setEditor(null)}/><section className="budget-editor"><header><div><span>BUDGET BUILDER</span><h2>{budgets.some(b=>b.id===editor.id)?'Edit budget':'Create a new budget'}</h2><p>Set category limits for the academic period.</p></div><button onClick={()=>setEditor(null)}><span className="material-symbols-rounded">close</span></button></header><div className="budget-editor__body"><div className="budget-fields"><label>Budget name<input value={editor.name} onChange={e=>setEditor({...editor,name:e.target.value})} placeholder="e.g. Term 3 Operating Budget"/></label><label>Academic term<select value={editor.term} onChange={e=>setEditor({...editor,term:e.target.value})}><option>Term 1</option><option>Term 2</option><option>Term 3</option></select></label><label>Year<input type="number" value={editor.year} onChange={e=>setEditor({...editor,year:Number(e.target.value)})}/></label></div><div className="budget-items-head"><div><h3>Category allocations</h3><p>Assign realistic spending limits to each area.</p></div><button onClick={()=>setEditor({...editor,items:[...editor.items,{id:`BI-${Date.now()}`,category:availableCategories.find(c=>!editor.items.some(i=>i.category===c))||'Other',allocated:0}]})}><span className="material-symbols-rounded">add</span>Add category</button></div><div>{editor.items.map((item,index)=><div className="budget-editor-item" key={item.id}><span>{String(index+1).padStart(2,'0')}</span><select value={item.category} onChange={e=>updateItem(item.id,{category:e.target.value})}>{availableCategories.map(c=><option key={c}>{c}</option>)}</select><div><span>KSh</span><input type="number" value={item.allocated||''} onChange={e=>updateItem(item.id,{allocated:Number(e.target.value)})} placeholder="0"/></div><button disabled={editor.items.length===1} onClick={()=>setEditor({...editor,items:editor.items.filter(i=>i.id!==item.id)})}><span className="material-symbols-rounded">delete</span></button></div>)}</div><div className="budget-editor-total"><div><span>Total planned budget</span><small>{editor.items.length} categories</small></div><strong>{formatKES(editor.items.reduce((sum,item)=>sum+item.allocated,0))}</strong></div></div><footer><button className="button button--light" onClick={()=>setEditor(null)}>Cancel</button><button className="button button--light" onClick={()=>persist(false)}><span className="material-symbols-rounded">save</span>Save draft</button><button className="button button--primary" onClick={()=>persist(true)}><span className="material-symbols-rounded">send</span>Submit for approval</button></footer></section></div>}</div>
}
